import Foundation

enum DailyWallpaperText {
  static var languageIndex: Int {
    languageIndex(setting: UserDefaults.standard.string(forKey: "flutter.language"),
                  preferredLanguage: Locale.preferredLanguages.first ?? "en")
  }

  static func languageIndex(setting: String?, preferredLanguage: String) -> Int {
    switch setting {
    case "korean": return 0
    case "english": return 1
    case "japanese": return 2
    case "traditionalChinese": return 3
    default:
      let language = preferredLanguage
      if language.hasPrefix("ko") { return 0 }
      if language.hasPrefix("ja") { return 2 }
      if language.hasPrefix("zh-Hant") || language.hasPrefix("zh-TW") || language.hasPrefix("zh-HK") { return 3 }
      return 1
    }
  }

  static var locale: Locale { Locale(identifier: ["ko_KR", "en_US", "ja_JP", "zh_TW"][languageIndex]) }
  static func value(_ key: String) -> String { values[key]?[languageIndex] ?? key }

  static func automationInstructions(appName: String, language: Int = languageIndex) -> String {
    let text = { (key: String) in values[key]![language] }
    return text("helperInstructions").replacingOccurrences(of: "{app}", with: appName)
      + "\n\n" + text("helperInstructionsEnd")
  }

  static let values: [String: [String]] = [
    "stage0": ["사진 준비", "Photo", "写真", "照片"],
    "stage1": ["단축어", "Shortcut", "ショートカット", "捷徑"],
    "stage2": ["표시 확인", "Verify", "表示確認", "確認"],
    "stage3": ["자동 갱신", "Automate", "自動更新", "自動更新"],
    "setupTitle0": ["먼저, 달력 배경을 준비해요", "Start with a calendar wallpaper", "まずカレンダーの壁紙を準備", "先準備月曆背景圖片"],
    "setupTitle1": ["이 배경을 업데이트할 단축어", "Connect your wallpaper shortcut", "壁紙を更新するショートカット", "連接背景更新捷徑"],
    "setupTitle2": ["잠금화면에 달력이 보이나요?", "Is the calendar on your Lock Screen?", "ロック画面に表示されましたか？", "鎖定畫面顯示月曆了嗎？"],
    "setupTitle3": ["이제, 앱을 열 때마다 갱신", "Refresh when you open Daily", "Dailyを開くたびに更新", "開啟 Daily 時更新"],
    "setupBody0": ["아래 이미지를 저장한 뒤, iPhone에서 사진 잠금화면으로 선택하세요.", "Save this image, then choose it for a photo Lock Screen on your iPhone.", "この画像を保存し、iPhoneで写真のロック画面に選びます。", "儲存下方圖片，再於 iPhone 選為照片鎖定畫面。"],
    "setupBody1": ["단축어는 하나만 연결합니다. 추가할 때 방금 준비한 사진 잠금화면을 선택하세요.", "Connect one shortcut. When adding it, select the photo Lock Screen you just prepared.", "接続するショートカットは1つです。追加時に準備した写真のロック画面を選びます。", "只需連接一個捷徑，加入時選擇剛準備好的照片鎖定畫面。"],
    "setupBody2": ["아래 버튼으로 실행한 뒤 잠금화면을 직접 확인해 주세요. 홈 화면은 변경하지 않습니다.", "Run the shortcut below, then check the Lock Screen yourself. Your Home Screen is not changed.", "下のボタンで実行した後、ロック画面を確認してください。ホーム画面は変更しません。", "執行下方捷徑後，請查看鎖定畫面。主畫面不會變更。"],
    "setupBody3": ["자동 갱신은 선택 사항이에요. 단축어 앱에서 한 번 연결하면 됩니다.", "Automatic refresh is optional. Connect it once in Shortcuts.", "自動更新は任意です。ショートカットで一度だけ接続します。", "自動更新為選用功能，在捷徑中連接一次即可。"],
    "savePhoto": ["달력 이미지를 사진에 저장", "Save Calendar to Photos", "カレンダー画像を写真に保存", "將月曆圖片儲存至照片"],
    "photoSaved": ["사진에 저장했어요", "Saved to Photos", "写真に保存しました", "已儲存至照片"],
    "photoSavedHelp": ["이제 아래 화면 안내에 따라 사진 잠금화면을 만들어 주세요.", "Now use the visual guide below to create your photo Lock Screen.", "下の画面ガイドで写真のロック画面を作成してください。", "接著依下方畫面指南建立照片鎖定畫面。"],
    "photoReady": ["사진 잠금화면을 준비했어요", "My Photo Lock Screen Is Ready", "写真のロック画面を準備しました", "已準備好照片鎖定畫面"],
    "photoGuide": ["배경 선택하는 화면 보기", "See Where to Choose the Wallpaper", "壁紙を選ぶ画面を見る", "查看選擇背景的畫面"],
    "shortcutReady": ["단축어를 추가했어요", "I Added the Shortcut", "ショートカットを追加しました", "已加入捷徑"],
    "shortcutReplace": ["단축어 추가 · 기존 버전 교체", "Add or Replace Shortcut", "ショートカットを追加・置換", "加入或取代捷徑"],
    "shortcutReplaceNote": ["이미 추가했더라도 이번 수정본으로 교체해 주세요. 앱 업데이트만으로 기존 단축어는 바뀌지 않습니다.", "Replace any older copy with this corrected shortcut. Updating Daily does not update imported shortcuts.", "追加済みでも今回の修正版に置き換えてください。Dailyの更新だけでは既存のショートカットは変わりません。", "即使已加入，也請以此次修正版取代。更新 Daily 不會更新已匯入的捷徑。"],
    "shortcutImportHelp": ["공유 창에서 ‘단축어’를 선택하세요. 추가 화면에서는 준비한 사진 배경을 지정하고, 같은 이름이 있으면 ‘대치’를 선택합니다.", "Choose Shortcuts in the share sheet. Select your photo wallpaper during setup, and Replace if the name already exists.", "共有画面でショートカットを選びます。準備した写真の壁紙を指定し、同じ名前がある場合は置き換えてください。", "在分享表單中選擇捷徑，指定已準備的照片背景；如有同名捷徑，請選擇取代。"],
    "applyNow": ["지금 잠금화면에 적용", "Apply to Lock Screen Now", "今すぐロック画面に適用", "立即套用至鎖定畫面"],
    "visibleYes": ["잠금화면에 달력이 보여요", "I Can See the Calendar", "ロック画面に表示されました", "鎖定畫面已顯示月曆"],
    "visibleNo": ["아직 보이지 않아요", "It Is Not Visible Yet", "まだ表示されません", "仍未顯示"],
    "visualConfirmed": ["사용자가 잠금화면 표시를 확인했어요", "You Confirmed the Lock Screen", "ロック画面の表示を確認済み", "您已確認鎖定畫面顯示"],
    "notVisibleHelp": ["단축어가 바꾸는 배경과 현재 사용 중인 잠금화면이 같아야 합니다. 먼저 사진 배경을 선택하고, 단축어의 업데이트 대상도 같은 배경으로 지정해 주세요.", "The shortcut target must match your active Lock Screen. Select the photo wallpaper, then select that same wallpaper in the shortcut.", "更新対象と使用中のロック画面は同じ必要があります。写真の壁紙を選び、ショートカットにも同じ壁紙を指定してください。", "捷徑目標必須與目前鎖定畫面相同。請啟用照片背景，並在捷徑中指定同一背景。"],
    "simulatorNote": ["시뮬레이터에서는 iOS의 사진 배경 표시가 실패할 수 있습니다. 동작 완료만으로 표시 성공으로 처리하지 않습니다. 실제 iPhone에서도 확인이 필요합니다.", "The Simulator can fail to render photo wallpapers. An action receipt is not visual confirmation; also check on a physical iPhone.", "シミュレータでは写真の壁紙描画が失敗する場合があります。動作完了は表示成功の証明ではありません。実機でも確認してください。", "模擬器可能無法呈現照片背景。動作完成不代表顯示成功，仍需在實體 iPhone 確認。"],
    "automationGuide": ["자동화 연결 화면 보기", "See Automation Setup Screens", "自動化の接続画面を見る", "查看自動化設定畫面"],
    "automationReady": ["자동화를 연결했어요", "I Connected the Automation", "自動化を接続しました", "已連接自動化"],
    "automationConfirmed": ["자동화 연결을 확인했어요", "Automation Connection Acknowledged", "自動化の接続を確認済み", "已確認自動化連接"],
    "later": ["자동 갱신은 나중에", "Set Up Automatic Refresh Later", "自動更新は後で", "稍後設定自動更新"],
    "options": ["배경 설정", "Wallpaper Options", "壁紙の設定", "背景設定"],
    "optionalHelper": ["기존 설정 도우미 (선택)", "Legacy Setup Helper (Optional)", "従来の設定ヘルパー（任意）", "原有設定輔助捷徑（選用）"],
    "setupRestart": ["사진 배경부터 다시 연결", "Reconnect from Photo Wallpaper", "写真の壁紙から接続し直す", "從照片背景重新連接"],
    "screenGuide": ["화면 안내", "Screen Guide", "画面ガイド", "畫面指南"],
    "guideTap": ["강조된 버튼을 누르면 다음 안내로 넘어갑니다. 실제 설정은 해당 앱에서 진행하세요.", "Tap the highlighted control to see the next step. Make the actual change in the indicated app.", "強調したボタンで次の案内へ進みます。実際の設定は各アプリで行ってください。", "點選醒目按鈕查看下一步。實際設定請在指定 App 內進行。"],
    "guideSettings": ["iPhone 설정 앱에서 ‘배경화면’을 누르세요.", "In iPhone Settings, tap Wallpaper.", "iPhoneの設定で「壁紙」をタップします。", "在 iPhone 設定中點選「背景圖片」。"],
    "guideAdd": ["‘새로운 배경화면 추가’를 누르세요.", "Tap Add New Wallpaper.", "「新しい壁紙を追加」をタップします。", "點選「加入新的背景圖片」。"],
    "guidePhotos": ["‘사진’을 선택하세요. 사진 셔플이 아닌 일반 사진입니다.", "Choose Photos, not Photo Shuffle.", "「写真」を選びます。写真シャッフルではありません。", "選擇「照片」，而非照片隨機顯示。"],
    "guideImage": ["방금 저장한 달력 이미지를 선택하세요.", "Select the calendar image you just saved.", "保存したカレンダー画像を選びます。", "選擇剛儲存的月曆圖片。"],
    "guideAddPhoto": ["달력 위치를 확인한 뒤 ‘추가’를 누르세요.", "Check the calendar position, then tap Add.", "カレンダーの位置を確認して「追加」をタップします。", "確認月曆位置後點選「加入」。"],
    "guideHome": ["홈 화면도 검토해 주세요. 별도로 설정하려면 ‘홈 화면 사용자화’를 누르세요.", "Review the Home Screen too. Use Customize Home Screen to set it separately.", "ホーム画面も確認します。別に設定する場合は「ホーム画面をカスタマイズ」を選びます。", "也請確認主畫面。若要另外設定，請點選「自訂主畫面」。"],
    "guideSelect": ["만든 사진 잠금화면을 현재 배경으로 선택한 뒤 Daily로 돌아오세요.", "Select this photo Lock Screen as your current wallpaper, then return to Daily.", "作成した写真のロック画面を使用中の壁紙に選び、Dailyに戻ります。", "將此照片鎖定畫面選為目前背景，然後返回 Daily。"],
    "guideAutomation": ["단축어 앱 아래쪽의 ‘자동화’를 누르세요.", "Tap Automation at the bottom of Shortcuts.", "ショートカット下部の「オートメーション」をタップします。", "點選捷徑底部的「自動化」。"],
    "guidePlus": ["오른쪽 위 + 또는 ‘새로운 자동화’를 누르세요.", "Tap + at the top right, or New Automation.", "右上の＋または「新規オートメーション」をタップします。", "點選右上角＋或「新增自動化」。"],
    "guideApp": ["실행 조건에서 ‘앱’을 선택하세요.", "Select App as the trigger.", "実行条件で「アプリ」を選びます。", "在觸發條件中選擇「App」。"],
    "guideChooseApp": ["앱 선택에서 아래 이름의 Daily를 선택하세요.", "Select the Daily app named below.", "下の名前のDailyアプリを選びます。", "選擇下列名稱的 Daily App。"],
    "guideOpened": ["‘열릴 때’를 선택하세요.", "Select Is Opened.", "「開いている」を選びます。", "選擇「已開啟」。"],
    "guideImmediate": ["‘즉시 실행’을 선택하고 ‘다음’을 누르세요.", "Select Run Immediately, then Next.", "「すぐに実行」を選び「次へ」をタップします。", "選擇「立即執行」後點選「下一步」。"],
    "guideChooseShortcut": ["DailyCalendar Wallpaper를 선택해 저장하세요. Setup 도우미가 아닙니다.", "Choose DailyCalendar Wallpaper and save. Do not choose the Setup helper.", "DailyCalendar Wallpaperを選んで保存します。Setupヘルパーではありません。", "選擇 DailyCalendar Wallpaper 並儲存，不是 Setup 輔助捷徑。"],
    "guideEnd": ["실제 설정을 마친 뒤 Daily에서 완료 여부를 확인해 주세요.", "After making the actual changes, confirm them in Daily.", "実際の設定を終えたらDailyで完了を確認してください。", "完成實際設定後，請返回 Daily 確認。"],
    "photoPermission": ["사진 추가 권한이 필요합니다. 설정에서 Daily의 사진 추가를 허용한 뒤 다시 저장하세요.", "Photo-add permission is needed. Allow Daily to add photos in Settings, then save again.", "写真の追加権限が必要です。設定で許可して再度保存してください。", "需要新增照片權限。請在設定中允許 Daily 新增照片後重新儲存。"],
    "photoPrivacy": ["직접 저장할 때만 사진에 복사합니다. iCloud 사진을 사용하면 해당 설정에 따라 동기화될 수 있습니다.", "Only Save copies an image to Photos. It may sync according to your iCloud Photos settings.", "保存ボタンでのみ写真にコピーします。iCloud写真の設定に従って同期される場合があります。", "只有點選儲存才會複製至照片，可能依您的 iCloud 照片設定進行同步。"],
    "replaceBrokenShortcut": ["단축어의 완료 확인 연결이 올바르지 않습니다. Daily의 잠금화면 설정에서 단축어를 새 버전으로 교체해 주세요.", "The shortcut completion connection is invalid. Replace the shortcut from Daily's Lock Screen settings.", "完了確認の接続が正しくありません。Dailyのロック画面設定からショートカットを置き換えてください。", "捷徑的完成確認連接無效，請從 Daily 鎖定畫面設定取代捷徑。"],
    "title": ["잠금화면 월간 캘린더", "Lock Screen Calendar", "ロック画面カレンダー", "鎖定畫面月曆"],
    "done": ["완료", "Done", "完了", "完成"],
    "cancel": ["취소", "Cancel", "キャンセル", "取消"],
    "enable": ["배경 업데이트 허용", "Allow Wallpaper Updates", "壁紙の更新を許可", "允許更新背景圖片"],
    "enabled": ["이미지 생성 허용됨", "Image generation enabled", "画像生成が有効", "已啟用圖片產生"],
    "disabled": ["배경 업데이트가 중지되어 있습니다.", "Wallpaper updates are paused.", "壁紙の更新は停止中です。", "背景圖片更新已暫停。"],
    "status": ["자동화 설정은 단축어 앱에서 확인해야 합니다.", "Check automation setup in Shortcuts.", "オートメーションの設定はショートカットで確認してください。", "請在捷徑中確認自動化設定。"],
    "generated": ["마지막 이미지 생성", "Last Image Generated", "最後の画像生成", "上次產生圖片"],
    "update_waiting": ["배경화면 적용 확인 중", "Waiting for Wallpaper Result", "壁紙の更新結果を確認中", "正在確認背景更新結果"],
    "updateCheckTitle": ["배경화면 적용을 확인하세요", "Check Wallpaper Application", "壁紙の適用を確認", "確認背景圖片套用狀態"],
    "update_systemReported": ["배경 변경 동작 완료", "Wallpaper Action Completed", "壁紙変更アクション完了", "背景變更動作已完成"],
    "update_failed": ["배경화면 단축어 실행 오류", "Wallpaper Shortcut Error", "壁紙ショートカットの実行エラー", "背景捷徑執行錯誤"],
    "update_cancelled": ["배경화면 적용이 취소되었습니다", "Wallpaper Update Cancelled", "壁紙の更新がキャンセルされました", "已取消背景更新"],
    "update_unconfirmed": ["배경화면 적용 완료를 확인하지 못했습니다", "Wallpaper Completion Not Confirmed", "壁紙の適用完了を確認できませんでした", "無法確認背景圖片已套用"],
    "updateNotVerified": ["아직 배경화면 적용을 확인하지 않았습니다. 단축어 추가와 이미지 생성만으로 배경화면이 바뀌지는 않습니다.", "Wallpaper application has not been confirmed. Adding a shortcut or generating an image does not apply it.", "壁紙の適用は未確認です。ショートカットの追加や画像生成だけでは壁紙は変わりません。", "尚未確認背景圖片已套用。加入捷徑或產生圖片不代表已套用。"],
    "updateFailureHelp": ["사진으로 만든 잠금화면이 있는지, 단축어에서 그 배경화면을 선택했는지와 실행 권한을 확인하세요. 단축어 추가만으로는 적용되지 않습니다.", "Check that you have a photo Lock Screen, selected it in the shortcut, and allowed execution. Adding the shortcut alone does not apply it.", "写真で作ったロック画面があり、ショートカットで選択済みか、実行が許可されているか確認してください。追加だけでは適用されません。", "請確認已建立照片鎖定畫面、在捷徑中選取該背景並允許執行。僅加入捷徑不會套用背景。"],
    "updateReportedHelp": ["iOS 배경 변경 동작이 완료되었습니다. 선택한 잠금화면을 직접 확인하세요. 다른 잠금화면이나 홈 화면을 보고 있다면 달력이 보이지 않을 수 있습니다. Daily는 실제 표시 화면을 읽을 수 없습니다.", "The iOS wallpaper action completed. Check the selected Lock Screen. Another Lock Screen or the Home Screen may not show the calendar. Daily cannot read the displayed wallpaper.", "iOSの壁紙変更が完了しました。選択したロック画面を確認してください。別のロック画面やホーム画面には表示されない場合があります。Dailyは実際の表示を読み取れません。", "iOS 背景變更動作已完成。請查看所選鎖定畫面；其他鎖定畫面或主畫面可能不會顯示月曆。Daily 無法讀取實際顯示畫面。"],
    "updateNotificationsOff": ["실패 알림 허용 설정", "Allow Failure Notifications", "失敗通知の許可設定", "允許失敗通知"],
    "updateWaitingHelp": ["단축어의 배경 변경 동작을 기다리고 있습니다. 2분 안에 완료 응답이 없으면 확인 불가 알림을 보냅니다.", "Waiting for the shortcut's wallpaper action. If no completion is received within two minutes, a notification reports that it could not be confirmed.", "ショートカットの壁紙変更を待っています。2分以内に完了応答がない場合は、確認できなかったことを通知します。", "正在等待捷徑的背景變更動作。若兩分鐘內未收到完成回應，將通知無法確認。"],
    "preview": ["배경 미리보기", "Wallpaper Preview", "壁紙プレビュー", "背景圖片預覽"],
    "refresh": ["미리보기 새로고침", "Refresh Preview", "プレビューを更新", "重新整理預覽"],
    "design": ["디자인", "Design", "デザイン", "設計"],
    "appearance": ["배경", "Background", "背景", "背景"],
    "dark": ["다크", "Dark", "ダーク", "深色"],
    "light": ["화이트", "Light", "ライト", "淺色"],
    "position": ["달력 세로 위치", "Calendar Position", "カレンダーの縦位置", "月曆垂直位置"],
    "layoutNote": ["시계·위젯과 겹치면 달력을 아래로 이동하세요. 큰 시계, 알림, 확대 효과에 따라 일부 내용이 가려질 수 있습니다.", "Move the calendar down if it overlaps the clock or widgets. A large clock, notifications or zoom effects may cover content.", "時計やウィジェットと重なる場合は位置を下げてください。大きな時計、通知、拡大効果で内容が隠れることがあります。", "若與時鐘或小工具重疊，請將月曆下移。大型時鐘、通知或縮放效果可能遮住內容。"],
    "privacyTitle": ["잠금화면에 일정을 표시할까요?", "Show Events on the Lock Screen?", "ロック画面に予定を表示しますか？", "在鎖定畫面顯示行程？"],
    "privacy": ["잠금 해제 전에도 일정 제목이 보입니다. 단축어는 선택한 잠금화면만 변경하며 OFF나 앱 삭제로 이전 배경이 복원되지는 않습니다. 이미지는 기기에서 생성합니다. 직접 ‘사진에 저장’을 누르면 사진 보관함에 복사되고 iCloud 사진 설정에 따라 동기화될 수 있습니다. 자동 갱신은 사진에 저장하지 않습니다.", "Event titles are visible while locked. The shortcut changes only the selected Lock Screen; disabling or deleting Daily does not restore the old wallpaper. Images are generated on-device. Save to Photos explicitly copies an image to your library, which may sync with iCloud Photos. Automatic refresh does not save to Photos.", "ロック中も予定名が表示されます。変更は選択したロック画面のみで、OFFやアプリ削除では元に戻りません。画像は端末で生成します。写真に保存した画像はiCloud写真の設定で同期される場合があります。自動更新では写真に保存しません。", "鎖定時可見行程標題。捷徑僅變更所選鎖定畫面，停用或刪除 Daily 不會還原。圖片在裝置上產生；手動儲存至照片後可能依 iCloud 照片設定同步。自動更新不會儲存至照片。"],
    "setup": ["설정 시작", "Set Up", "設定を始める", "開始設定"],
    "guide": ["자동화 설정 가이드", "Automation Setup", "オートメーション設定", "自動化設定指南"],
    "addHelper": ["설정 도우미 추가", "Add Setup Helper", "設定ヘルパーを追加", "加入設定輔助捷徑"],
    "runHelper": ["단축어에서 안내 시작", "Start Guide in Shortcuts", "ショートカットで案内を開始", "在捷徑中開始指南"],
    "helperStep": ["단축어 안에서 설정 안내", "Setup Help Inside Shortcuts", "ショートカット内で設定を案内", "在捷徑內引導設定"],
    "helperAddBody": ["DailyCalendar Wallpaper Setup을 추가하세요. 연결 방법과 적용 테스트를 단축어 안에서 선택할 수 있습니다. 이미 추가했다면 다음으로 넘어가세요.", "Add DailyCalendar Wallpaper Setup for connection instructions and a test menu inside Shortcuts. If already added, continue to the next step.", "DailyCalendar Wallpaper Setupを追加すると、接続手順とテストをショートカット内で選べます。追加済みの場合は次へ進んでください。", "加入 DailyCalendar Wallpaper Setup，即可在捷徑內選擇連接指南及測試。若已加入，請繼續下一步。"],
    "helperRunBody": ["아래 버튼으로 설정 도우미를 실행하세요. ‘연결 방법 보기’에서 자동화 연결 순서를 확인하거나 ‘지금 테스트’를 선택할 수 있습니다. 자동화에는 Setup이 아닌 DailyCalendar Wallpaper를 연결하세요.", "Run the helper below to view connection steps or test an update. Connect DailyCalendar Wallpaper to your automation, not the Setup helper.", "下のボタンでヘルパーを実行し、接続手順またはテストを選びます。オートメーションにはSetupではなくDailyCalendar Wallpaperを設定してください。", "執行下方輔助捷徑以查看連接步驟或進行測試。自動化應連接 DailyCalendar Wallpaper，而非 Setup 輔助捷徑。"],
    "manualGuide": ["직접 설정 방법 보기", "View Manual Setup Steps", "手動設定の手順を見る", "查看手動設定步驟"],
    "showConnectionGuide": ["연결 방법 보기", "View Connection Steps", "接続手順を見る", "查看連接步驟"],
    "closeHelper": ["안내 닫기", "Close Guide", "案内を閉じる", "關閉指南"],
    "helperPrompt": ["Daily 잠금화면 설정 도우미\n무엇을 할까요?", "Daily Lock Screen Setup\nWhat would you like to do?", "Dailyロック画面の設定\n何をしますか？", "Daily 鎖定畫面設定\n您想做什麼？"],
    "helperInstructions": ["단축어 앱에서 아래 순서대로 한 번만 설정하세요.\n\n1. 자동화 → + 또는 새로운 자동화 → 앱\n2. {app} 선택 → 열릴 때 → 즉시 실행\n3. 다음 → DailyCalendar Wallpaper 선택 → 저장\n\nSetup 도우미나 빈 자동화를 선택하지 마세요.", "Set this up once in Shortcuts:\n\n1. Automation → + or New Automation → App\n2. Select {app} → Is Opened → Run Immediately\n3. Next → choose DailyCalendar Wallpaper → save\n\nDo not select the Setup helper or a blank automation.", "ショートカットで一度だけ設定してください。\n\n1. オートメーション → ＋または新規作成 → アプリ\n2. {app} → 開いている → すぐに実行\n3. 次へ → DailyCalendar Wallpaper → 保存\n\nSetupヘルパーや空のオートメーションは選ばないでください。", "請在捷徑中設定一次：\n\n1. 自動化 → ＋或新增自動化 → App\n2. 選擇 {app} → 已開啟 → 立即執行\n3. 下一步 → 選擇 DailyCalendar Wallpaper → 儲存\n\n請勿選擇 Setup 輔助捷徑或空白自動化。"],
    "helperInstructionsEnd": ["계속을 누르면 안내가 닫힙니다. 자동화 화면으로 이동해 직접 연결하세요. 안내를 읽는 것만으로 자동화가 생성되지는 않습니다. iOS 언어·버전에 따라 메뉴 이름이 다를 수 있습니다.", "Continue closes this guide. Go to Automation and connect it yourself. Reading this guide does not create an automation. Menu names may vary by iOS language and version.", "続けると案内が閉じます。オートメーション画面で手動で接続してください。案内を見るだけでは自動化は作成されません。メニュー名はiOSの言語やバージョンで異なる場合があります。", "點選繼續將關閉指南。請前往自動化畫面自行連接。閱讀指南不會建立自動化。選單名稱可能因 iOS 語言及版本而異。"],
    "helperDisabled": ["먼저 Daily 설정 → 잠금화면 월간 캘린더에서 ‘배경 업데이트 허용’을 켜고 안내에 동의하세요. 이 도우미는 동의를 대신 설정하지 않습니다.", "First enable Allow Wallpaper Updates in Daily Settings → Lock Screen Calendar and accept the notice. This helper does not grant consent for you.", "まずDaily設定のロック画面カレンダーで壁紙更新を許可し、案内に同意してください。ヘルパーが代わりに同意することはありません。", "請先在 Daily 設定的鎖定畫面月曆中啟用背景更新並同意說明。輔助捷徑不會代您同意。"],
    "helperTestWarning": ["DailyCalendar Wallpaper가 미리 추가되어 있어야 합니다. 계속하면 선택한 잠금화면 배경이 달력 이미지로 바뀌며 잠금 상태에서도 일정 제목이 보입니다. 실행 후 잠금화면을 직접 확인하세요. 테스트 성공은 자동화 등록을 의미하지 않습니다.", "DailyCalendar Wallpaper must already be added. Continuing changes the selected Lock Screen to a calendar image, exposing event titles while locked. Check the Lock Screen afterward. A successful test does not verify automation registration.", "DailyCalendar Wallpaperを先に追加してください。続けると選択したロック画面がカレンダーに変わり、ロック中も予定名が表示されます。実行後に画面を確認してください。テスト成功は自動化の登録確認ではありません。", "請先加入 DailyCalendar Wallpaper。繼續後會將所選鎖定畫面改為月曆，鎖定時仍可看到行程標題。執行後請查看鎖定畫面。測試成功不代表已確認自動化登錄。"],
    "add": ["단축어 추가하기", "Add Shortcut", "ショートカットを追加", "加入捷徑"],
    "open": ["단축어 앱 열기", "Open Shortcuts", "ショートカットを開く", "開啟捷徑"],
    "next": ["다음", "Next", "次へ", "下一步"],
    "back": ["이전", "Back", "戻る", "上一步"],
    "test": ["지금 업데이트", "Update Now", "今すぐ更新", "立即更新"],
    "testSetup": ["지금 테스트", "Test Now", "今すぐテスト", "立即測試"],
    "step1": ["완성된 단축어 추가", "Add the Ready-Made Shortcut", "完成したショートカットを追加", "加入已完成的捷徑"],
    "wallpaperSelectionHelp": ["배경화면 선택 도움말", "Wallpaper Selection Help", "壁紙選択のヘルプ", "背景圖片選擇說明"],
    "photoWallpaperTitle0": ["사진 잠금화면을 먼저 준비하세요", "Prepare a Photo Lock Screen First", "先に写真のロック画面を準備", "先準備照片鎖定畫面"],
    "photoWallpaperBody0": ["단축어는 ‘사진’으로 만든 잠금화면을 선택합니다. 기본 시스템 배경만 있으면 목록이 비거나 선택할 수 없습니다. iPhone 설정 앱에서 아래 순서로 들어가세요. 이미 사진 잠금화면이 있다면 아래 버튼으로 바로 넘어갈 수 있습니다.", "The shortcut needs a Lock Screen created with Photos. With only a system wallpaper, the list can be empty or unavailable. Follow this path in iPhone Settings. If you already have a photo Lock Screen, use the button below to continue.", "ショートカットには「写真」で作ったロック画面が必要です。標準の壁紙しかない場合、一覧が空になるか選択できません。iPhoneの設定で以下の順に進みます。写真のロック画面がある場合は下のボタンで進めます。", "捷徑需要以「照片」建立的鎖定畫面。若只有系統背景圖片，清單可能空白或無法選取。請在 iPhone 設定中依下列路徑操作。若已有照片鎖定畫面，可按下方按鈕繼續。"],
    "photoWallpaperTitle1": ["‘사진’으로 새 배경을 만드세요", "Choose Photos for the New Wallpaper", "新しい壁紙で「写真」を選択", "選擇「照片」建立新背景圖片"],
    "photoWallpaperBody1": ["‘사진’을 누르고 사용할 사진 한 장을 선택하세요. 사진 셔플·이모티콘·날씨·천체 등 다른 종류는 선택하지 마세요. 사진이 없다면 먼저 사진 앱에 사용할 사진 한 장을 준비하세요.", "Tap Photos and choose one photo. Do not choose Photo Shuffle, Emoji, Weather or Astronomy. If there are no photos, first add a photo to the Photos app.", "「写真」をタップして写真を1枚選びます。「写真シャッフル」「絵文字」「天気」「アストロノミー」などは選ばないでください。写真がない場合は、先に写真アプリに1枚用意してください。", "點選「照片」並選擇一張照片。請勿選取「照片隨機顯示」、「表情符號」、「天氣」或「天文」。若沒有照片，請先在照片 App 中準備一張照片。"],
    "photoWallpaperTitle2": ["저장한 뒤 Daily로 돌아오세요", "Save, Then Return to Daily", "保存してDailyに戻る", "儲存後返回 Daily"],
    "photoWallpaperBody2": ["‘추가’를 눌러 저장하고 홈 화면 설정을 직접 확인하세요. 홈 화면을 따로 지정하려면 ‘홈 화면 사용자화’를 선택합니다. Daily로 돌아와 단축어를 추가할 때 방금 만든 사진 잠금화면을 선택하세요. 이 안내는 배경화면을 대신 만들거나 변경하지 않습니다.", "Tap Add to save, then review the Home Screen setting. Choose Customize Home Screen to set it separately. Return to Daily and select this new photo Lock Screen when adding the shortcut. This guide does not create or change wallpapers for you.", "「追加」で保存し、ホーム画面の設定を確認します。別に設定する場合は「ホーム画面をカスタマイズ」を選びます。Dailyに戻り、ショートカット追加時に作成した写真のロック画面を選びます。この案内が壁紙を作成・変更することはありません。", "點選「加入」儲存並確認主畫面設定。若要另外設定，請選擇「自訂主畫面」。返回 Daily，加入捷徑時選擇剛建立的照片鎖定畫面。此指南不會代您建立或變更背景圖片。"],
    "settingsApp": ["설정", "Settings", "設定", "設定"],
    "wallpaperSettings": ["배경화면", "Wallpaper", "壁紙", "背景圖片"],
    "addWallpaper": ["새로운 배경화면 추가", "Add New Wallpaper", "新しい壁紙を追加", "加入新的背景圖片"],
    "photosWallpaper": ["사진", "Photos", "写真", "照片"],
    "choosePhoto": ["사용할 사진 한 장 선택", "Choose One Photo", "写真を1枚選択", "選擇一張照片"],
    "saveWallpaper": ["추가", "Add", "追加", "加入"],
    "customizeHomeScreen": ["홈 화면 사용자화", "Customize Home Screen", "ホーム画面をカスタマイズ", "自訂主畫面"],
    "photoWallpaperGuideNote": ["Daily의 안내 화면입니다. 실제 설정은 iPhone 설정 앱에서 진행하세요.", "This is Daily's guide. Make these changes in iPhone Settings.", "これはDailyの案内です。実際の操作はiPhoneの設定で行ってください。", "這是 Daily 的指南，請在 iPhone 設定中進行實際操作。"],
    "photoWallpaperReady": ["사진 잠금화면 준비됨 · 단축어 추가", "Photo Lock Screen Ready · Add Shortcut", "写真のロック画面を準備済み・追加", "已準備照片鎖定畫面 · 加入捷徑"],
    "photoWallpaperReturn": ["목록이 비거나 회색이면 사진 잠금화면이 저장됐는지 확인한 뒤 다시 추가하세요. Daily는 생성 여부를 자동으로 확인할 수 없습니다.", "If the list is empty or greyed out, check that the photo Lock Screen was saved, then try adding again. Daily cannot verify its creation automatically.", "一覧が空またはグレーの場合、写真のロック画面が保存されたか確認して再度追加してください。Dailyは作成を自動確認できません。", "若清單空白或呈灰色，請確認已儲存照片鎖定畫面後重新加入。Daily 無法自動確認是否已建立。"],
    "step1Body": ["아래 버튼에서 단축어 앱으로 파일을 열고 ‘단축어 추가’를 선택하세요. 요청되면 업데이트할 사진 기반 잠금화면을 선택합니다. 일정은 단축어 파일에 포함되지 않습니다. 이미 추가했다면 다음으로 넘어가세요.", "Open the file in Shortcuts below and choose Add Shortcut. If prompted, select a photo-based Lock Screen to update. No event data is included. If already added, continue to the next step.", "下のボタンからファイルをショートカットで開き、追加してください。求められた場合は写真のロック画面を選びます。予定データは含まれません。追加済みの場合は次へ進んでください。", "按下方按鈕，透過捷徑開啟檔案並加入。若系統詢問，請選擇照片鎖定畫面。檔案不含行程資料。若已加入，請繼續下一步。"],
    "step2": ["개인 자동화 만들기", "Create a Personal Automation", "個人用オートメーションを作成", "建立個人自動化"],
    "step2Body": ["단축어 앱에서 ‘자동화’를 열고 + 또는 새로운 자동화를 선택합니다. 이 단계는 iOS 정책에 따라 직접 설정해야 합니다.", "In Shortcuts, open Automation, then tap + or New Automation. iOS requires you to configure this step yourself.", "ショートカットの「オートメーション」で＋または新規作成を選びます。この手順はiOSの制約により手動で行います。", "在捷徑中開啟「自動化」，點選＋或新增自動化。iOS 要求您手動完成此步驟。"],
    "step3": ["Daily를 열 때 실행", "Run When Daily Opens", "Dailyを開いたときに実行", "開啟 Daily 時執行"],
    "step3Body": ["‘앱’을 선택하고 이 Daily 앱을 지정한 뒤 ‘열릴 때’와 ‘즉시 실행’을 선택합니다. 테스트 앱과 App Store 앱을 혼동하지 마세요.", "Choose App, select this Daily app, then Is Opened and Run Immediately. Select the correct test or App Store app.", "「アプリ」でこのDailyを選び、「開いている」と「すぐに実行」を選択します。テスト版とApp Store版を区別してください。", "選擇「App」及此 Daily App，再選擇「已開啟」及「立即執行」。請分清測試版與 App Store 版。"],
    "step4": ["단축어 선택 및 테스트", "Select the Shortcut and Test", "ショートカットを選択してテスト", "選擇捷徑並測試"],
    "step4Body": ["DailyCalendar Wallpaper를 선택해 자동화를 저장하세요. ‘지금 테스트’ 후 잠금화면을 직접 확인합니다. 안내를 끝냈다는 이유만으로 설치나 적용 완료로 표시하지 않습니다.", "Select DailyCalendar Wallpaper and save the automation. Run Test Now and check the Lock Screen. Finishing this guide does not verify installation or wallpaper application.", "DailyCalendar Wallpaperを選んで保存し、テスト後にロック画面を確認します。案内の完了だけではインストールや適用を確認できません。", "選擇 DailyCalendar Wallpaper 並儲存自動化。立即測試後請親自查看鎖定畫面。完成指南不代表已確認安裝或套用成功。"],
    "automation": ["자동화", "Automation", "オートメーション", "自動化"],
    "newAutomation": ["새로운 자동화", "New Automation", "新規オートメーション", "新增自動化"],
    "app": ["앱", "App", "アプリ", "App"],
    "opened": ["열릴 때", "Is Opened", "開いている", "已開啟"],
    "immediate": ["즉시 실행", "Run Immediately", "すぐに実行", "立即執行"],
    "guideNote": ["메뉴 순서 안내이며 실제 시스템 화면이 아닙니다. iOS 버전·언어에 따라 명칭이 다를 수 있습니다.", "Menu guide, not a system screenshot. Names may vary with iOS version and language.", "メニュー順の案内であり、実際のシステム画面ではありません。名称はiOSのバージョンや言語で異なる場合があります。", "這是選單流程指南，並非系統截圖。名稱可能隨 iOS 版本與語言而異。"],
    "timing": ["앱을 열 때 저장된 데이터로 갱신합니다. 앱을 닫은 동안의 변경은 다음 단축어 실행까지 반영되지 않습니다. 잠긴 상태에서는 iOS가 인증을 요구할 수 있습니다.", "Updates from saved data when the app opens. Changes while closed appear at the next shortcut run. iOS may require authentication while locked.", "アプリ起動時の保存済みデータで更新します。終了中の変更は次の実行時に反映されます。ロック中は認証が必要な場合があります。", "開啟 App 時依已儲存資料更新。關閉期間的變更會在下次執行捷徑時反映。鎖定時 iOS 可能要求驗證。"],
    "remove": ["완전히 제거", "Remove Completely", "完全に削除", "完全移除"],
    "removeHelper": ["추가했다면 DailyCalendar Wallpaper Setup 도우미도 삭제하세요.", "If added, also delete the DailyCalendar Wallpaper Setup helper.", "追加した場合はDailyCalendar Wallpaper Setupヘルパーも削除してください。", "若已加入，也請刪除 DailyCalendar Wallpaper Setup 輔助捷徑。"],
    "removeTitle": ["배경 업데이트 중지 및 제거", "Stop Updates and Remove", "更新を停止して削除", "停止更新並移除"],
    "removeBody": ["먼저 이 기능을 끄세요. 단축어 앱의 자동화에서 Daily 자동화를 비활성화하거나 삭제한 뒤 DailyCalendar Wallpaper 단축어도 삭제합니다. 이 앱은 iOS 자동화를 대신 삭제할 수 없습니다. 이전 배경은 iOS 설정 > 배경화면에서 직접 선택해야 합니다.", "Turn this feature off first. In Shortcuts > Automation, disable or delete the Daily automation, then delete DailyCalendar Wallpaper. Daily cannot delete iOS automations for you. Restore your previous wallpaper in iOS Settings > Wallpaper.", "まず機能をOFFにします。ショートカットのオートメーションからDailyを無効化または削除し、DailyCalendar Wallpaperも削除します。アプリはiOSの自動化を削除できません。以前の壁紙はiOSの設定から選び直してください。", "請先關閉此功能。在捷徑的自動化中停用或刪除 Daily 自動化，再刪除 DailyCalendar Wallpaper。App 無法代您刪除 iOS 自動化。請在 iOS 設定的背景圖片中還原原背景。"],
    "clear": ["앱 내부 배경 데이터 삭제", "Delete Local Wallpaper Data", "アプリ内の壁紙データを削除", "刪除 App 內背景資料"],
    "clearConfirm": ["일정은 유지하고 배경 설정·캐시만 삭제합니다. 잠금화면에 이미 적용된 이미지는 그대로 남습니다.", "Only wallpaper settings and cache are removed. Events and the already-applied wallpaper remain.", "壁紙の設定とキャッシュのみ削除します。予定と適用済みの壁紙は残ります。", "僅移除背景設定與快取，行程及已套用的背景會保留。"],
    "cleared": ["앱 내부 데이터 삭제 완료 · iOS 자동화는 직접 삭제하세요.", "Local data removed. Delete the iOS automation separately.", "アプリ内データを削除しました。iOSの自動化は別途削除してください。", "已移除本機資料，請另外刪除 iOS 自動化。"],
    "unsupported": ["iOS 16 이상을 사용하는 iPhone에서 지원합니다.", "Requires an iPhone with iOS 16 or later.", "iOS 16以降のiPhoneが必要です。", "需要搭載 iOS 16 或更新版本的 iPhone。"],
    "installError": ["단축어 파일을 열 수 없습니다. 다시 시도해 주세요.", "Could not open the shortcut file. Try again.", "ショートカットを開けません。再試行してください。", "無法開啟捷徑檔案，請重試。"],
    "dataError": ["일정 데이터를 읽지 못했습니다. Daily를 열어 데이터 준비를 마친 뒤 다시 시도하세요.", "Could not read events. Open Daily, finish loading your data and try again.", "予定を読み込めません。Dailyでデータの準備を完了してから再試行してください。", "無法讀取行程。請開啟 Daily，待資料準備完成後重試。"],
    "openError": ["단축어 앱을 열지 못했습니다. 설치 여부를 확인하세요.", "Could not open Shortcuts. Check that it is installed.", "ショートカットを開けません。インストールを確認してください。", "無法開啟捷徑，請確認已安裝。"],
  ]
}
