import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import '../settings/app_settings.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('ko'),
    Locale('en'),
    Locale('ja'),
    Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        const AppLocalizations(Locale('ko'));
  }

  String get languageCode {
    if (locale.languageCode == 'zh') return 'zh_Hant';
    return locale.languageCode;
  }

  String text(String korean, {Map<String, Object>? args}) {
    var translated = _translations[languageCode]?[korean] ?? korean;
    for (final entry in (args ?? const <String, Object>{}).entries) {
      translated = translated.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return translated;
  }

  String languageName(AppLanguage language) => switch (language) {
    AppLanguage.system => text('시스템 설정에 따름'),
    AppLanguage.korean => '한국어',
    AppLanguage.english => 'English',
    AppLanguage.japanese => '日本語',
    AppLanguage.traditionalChinese => '繁體中文',
  };

  String themeName(AppThemeMode mode) => switch (mode) {
    AppThemeMode.system => text('자동'),
    AppThemeMode.light => text('화이트'),
    AppThemeMode.dark => text('다크'),
  };

  String navigationName(MonthNavigationMode mode) => switch (mode) {
    MonthNavigationMode.horizontal => text('좌우 슬라이드'),
    MonthNavigationMode.vertical => text('상하 스크롤'),
  };

  String textSizeName(AppTextSize size) => switch (size) {
    AppTextSize.basic => text('기본'),
    AppTextSize.large => text('크게'),
    AppTextSize.extraLarge => text('더 크게'),
  };

  String calendarViewName(CalendarViewMode mode) => switch (mode) {
    CalendarViewMode.week => text('주간'),
    CalendarViewMode.month => text('월간'),
    CalendarViewMode.day => text('일간'),
  };

  String compactCalendarViewName(CalendarViewMode mode) {
    if (languageCode == 'ko') {
      return switch (mode) {
        CalendarViewMode.week => '주',
        CalendarViewMode.month => '월',
        CalendarViewMode.day => '일',
      };
    }
    return switch (mode) {
      CalendarViewMode.week => text('주 보기'),
      CalendarViewMode.month => text('월 보기'),
      CalendarViewMode.day => text('일 보기'),
    };
  }

  String lockMethodName(AppLockMethod method) => switch (method) {
    AppLockMethod.noPin => text('PIN 없이 잠금'),
    AppLockMethod.appPin => text('PIN 잠금'),
    AppLockMethod.system => text('시스템 잠금 비밀번호'),
  };

  String categoryName({required String id, required String label}) {
    if (id == 'basic' && label == '기본') {
      return text('기본');
    }
    if (id == 'holiday') {
      return text('공휴일');
    }
    return label;
  }

  String holidayTitle(String title) {
    return title.split(' · ').map((part) => text(part)).join(' · ');
  }

  String eventTitle(String title, {required bool holiday}) {
    return holiday ? holidayTitle(title) : title;
  }
}

extension AppLocalizationContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String korean, {Map<String, Object>? args}) =>
      l10n.text(korean, args: args);
}

Locale? localeForLanguage(AppLanguage language) => switch (language) {
  AppLanguage.system => null,
  AppLanguage.korean => const Locale('ko'),
  AppLanguage.english => const Locale('en'),
  AppLanguage.japanese => const Locale('ja'),
  AppLanguage.traditionalChinese => const Locale.fromSubtags(
    languageCode: 'zh',
    scriptCode: 'Hant',
  ),
};

Locale resolvedLocaleForLanguage(AppLanguage language, Locale systemLocale) {
  final explicit = localeForLanguage(language);
  if (explicit != null) return explicit;
  if (systemLocale.languageCode == 'zh') {
    return const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant');
  }
  return AppLocalizations.supportedLocales.firstWhere(
    (locale) => locale.languageCode == systemLocale.languageCode,
    orElse: () => const Locale('en'),
  );
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      const {'ko', 'en', 'ja', 'zh'}.contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const Map<String, Map<String, String>> _translations = {
  'en': {
    '업데이트 중입니다': 'Updating Daily',
    '업데이트 확인 중': 'Checking for updates',
    '최신 백업을 복원하고 있습니다.': 'Restoring the latest backup.',
    '안전 스냅샷을 만들고 있습니다.': 'Creating a safe snapshot.',
    '일정을 Todo 형식으로 업데이트하고 있습니다.': 'Updating events to Todo format.',
    '업데이트 결과를 확인하고 있습니다.': 'Validating the update.',
    '업데이트된 일정을 백업하고 있습니다.': 'Backing up updated events.',
    '업데이트가 완료되었습니다.': 'Update complete.',
    '업데이트를 완료하지 못했습니다': 'Could not complete the update',
    '다시 시도': 'Try again',
    '시스템 설정에 따름': 'Follow system settings',
    '언어': 'Language',
    '설정': 'Settings',
    '알림 설정': 'Notification Settings',
    '계정 설정': 'Account Settings',
    '알림': 'Notifications',
    '일정 알림, 아침 브리핑, D-day 알림':
        'Event reminders, morning briefing, and D-day alerts',
    '계정': 'Account',
    'Siri 단축어 설정': 'Siri Shortcut Setup',
    '자동 등록된 시그널 단축어와 사용 방법을 확인합니다.':
        'Review the automatically registered Signal shortcut and how to use it.',
    '시그널 단축어 사용': 'Use Signal Shortcut',
    '시그널은 앱 설치와 함께 자동으로 등록되므로 직접 만들 필요가 없습니다.':
        'Signal is registered automatically with the app, so you do not need to create it yourself.',
    '1. Siri에게 “Daily에서 시그널 실행”이라고 말합니다.':
        '1. Say “Run Signal in Daily” to Siri.',
    '2. Siri가 질문하면 원하는 일정 명령을 이어서 말합니다.':
        '2. When Siri asks, continue with the calendar command you want.',
    '예: “내일 오전 9시에 헬스장 일정을 추가해줘.”':
        'Example: “Add a gym event tomorrow at 9 AM.”',
    '단축어 앱에서 Daily의 Signal App Shortcut이 등록되었는지 확인할 수 있습니다.':
        'You can verify the Daily Signal App Shortcut in the Shortcuts app.',
    '단축어 앱에서 확인': 'Check in Shortcuts',
    '일정을 놓을 날짜': 'Drop on a date',
    '시그널 단축어를 추가하고 Siri에서 Daily 명령을 사용합니다.':
        'Add the Signal shortcut to use Daily commands with Siri.',
    '시그널 단축어 추가 화면을 열 수 없습니다.':
        'Could not open the Add Signal Shortcut screen.',
    '시그널 단축어 추가': 'Add Signal Shortcut',
    '단축어 앱에서 다음 순서로 구성하세요.': 'Set it up in the Shortcuts app in this order.',
    '1. 새 단축어를 만들고 이름을 시그널로 지정합니다.': '1. Create a shortcut and name it Signal.',
    '2. 텍스트 받아쓰기 동작을 추가합니다.': '2. Add the Dictate Text action.',
    '3. Daily Signal 동작을 추가하고 받아쓰기한 텍스트를 Signal phrase에 연결합니다.':
        '3. Add the Daily Signal action and connect Dictated Text to Signal phrase.',
    '단축어 생성 화면 열기': 'Open Shortcut Editor',
    '단축어 앱을 열 수 없습니다.': 'Could not open the Shortcuts app.',
    'Siri 작업 기록': 'Siri Activity',
    'Siri 작업 상세': 'Siri Action Details',
    '작업': 'Action',
    '상태': 'Status',
    '실행 시각': 'Executed at',
    '요약': 'Summary',
    '결과': 'Result',
    '시작': 'Start',
    '종료': 'End',
    '종일 일정': 'All-day event',
    '예': 'Yes',
    '아니요': 'No',
    '기록 전체 삭제': 'Clear all activity',
    'Siri 작업 기록 삭제': 'Clear Siri activity',
    '저장된 Siri 작업 기록을 모두 삭제하시겠습니까?': 'Delete all saved Siri activity?',
    '성공': 'Success',
    '실패': 'Failed',
    'Siri와 자동화로 실행한 Daily 작업을 날짜별로 확인합니다.':
        'Review Daily actions run by Siri and automations by date.',
    '날짜 선택': 'Choose date',
    '전체 날짜 보기': 'Show all dates',
    '기록된 Siri 작업이 없습니다.': 'No Siri activity recorded.',
    '오늘 일정 조회': "Today's events",
    '내일 일정 조회': "Tomorrow's events",
    '날짜별 일정 조회': 'Events by date',
    '다음 일정 조회': 'Next event',
    'D-day 조회': 'D-day events',
    '달력 열기': 'Open calendar',
    'Siri 작업': 'Siri action',
    '지금 듣는 중...': 'Listening...',
    '시그널 처리 중...': 'Processing Signal...',
    '다시 말씀해 주세요': 'Please try again',
    '필요한 정보를 이어서 말씀해 주세요.': 'Please continue with the missing information.',
    '음성 명령을 처리하지 못했습니다.': 'The voice command could not be processed.',
    '듣기 중지': 'Stop listening',
    '다시 듣기': 'Listen again',
    '음성 듣기가 중단되었습니다.': 'Listening was interrupted.',
    '이 명령을 실행할까요?': 'Run this command?',
    '인증 또는 작업이 취소되었습니다.': 'Authentication or the action was cancelled.',
    '기기 인증을 완료하지 못했습니다.': 'Device authentication could not be completed.',
    '작업을 취소했습니다.': 'The action was cancelled.',
    '일정은 저장했지만 알림 또는 동기화 처리가 보류되었습니다.':
        'The event was saved, but notification or sync processing is pending.',
    '일정은 저장했으며 클라우드 동기화는 연결 후 재시도됩니다.':
        'The event was saved. Cloud sync will retry after an account is connected.',
    '실행 확인': 'Confirm action',
    '듣기 완료': 'Finish listening',
    '텍스트로 입력': 'Type instead',
    'Daily에 요청할 내용을 입력하세요.': 'Enter a request for Daily.',
    'Apple, Google, 동기화 및 계정 관리': 'Apple, Google, sync, and account management',
    '화면': 'Appearance',
    '테마': 'Theme',
    '자동': 'System',
    '화이트': 'Light',
    '다크': 'Dark',
    '달력': 'Calendar',
    '주 시작 요일': 'First day of week',
    '일': 'Sun',
    '월': 'Mon',
    '주 보기': 'Week',
    '월 보기': 'Month',
    '일 보기': 'Day',
    '음력 표시': 'Show lunar dates',
    '월 달력의 각 날짜에 음력 날짜를 함께 표시합니다.':
        'Show lunar dates alongside dates in the month calendar.',
    '인접한 달 날짜 표시': 'Show adjacent month dates',
    '상하 스크롤에서는 월 경계를 명확히 구분하기 위해 사용할 수 없습니다.':
        'Unavailable in vertical scrolling to keep month boundaries clear.',
    '월간 달력의 첫주와 마지막 주에 이전·다음 달을 표시합니다.':
        'Show previous and next month dates in the first and last weeks.',
    '월간 이동 방식': 'Month navigation',
    '좌우 슬라이드': 'Swipe horizontally',
    '상하 스크롤': 'Scroll vertically',
    '첫 화면': 'Start screen',
    '앱을 열었을 때 먼저 보여줄 화면': 'Screen shown when the app opens',
    '기본 보기': 'Default view',
    '주간·일간 표시 방식': 'Week/day layout',
    '목록': 'List',
    '스케줄': 'Schedule',
    '종일 일정 표시': 'Show all-day events',
    '종일 일정 숨기기': 'Hide all-day events',
    '앱을 열었을 때 먼저 보여줄 달력 보기': 'Calendar view shown when the app opens',
    '주간': 'Week',
    '월간': 'Month',
    '일간': 'Day',
    '전체 UI 글자 크기': 'Interface text size',
    '기본': 'Default',
    '가운데': 'Center',
    '일정 제목 정렬': 'Event title alignment',
    '일정 정렬 우선순위': 'Event sorting priority',
    '분류 우선': 'Category first',
    '시간 우선': 'Time first',
    '길게 눌러 순서 변경': 'Touch and hold to reorder',
    '크게': 'Large',
    '더 크게': 'Larger',
    '개인정보': 'Privacy',
    '익명 사용성 분석 허용': 'Allow anonymous usage analytics',
    '일정 내용, 검색어, 계정 정보 없이 화면과 기능 사용, 오류 범주, 성능 정보만 수집합니다.':
        'Collect screen and feature usage, error categories, and performance only, without event content, searches, or account information.',
    '분석 데이터 삭제': 'Delete analytics data',
    '이 기기에 전송 대기 중인 익명 분석 데이터를 삭제합니다.':
        'Delete anonymous analytics waiting to be sent from this device.',
    '이 기기에 전송 대기 중인 익명 분석 데이터를 삭제할까요? 이미 전송되어 집계된 데이터는 계정이나 기기와 연결되지 않아 특정 사용자를 식별하거나 되돌릴 수 없습니다.':
        'Delete anonymous analytics waiting on this device? Data already sent is aggregated without an account or device link, so it cannot identify or be restored for a specific user.',
    '전송 대기 분석 데이터를 삭제했습니다.': 'Analytics data waiting to be sent was deleted.',
    '앱 잠금': 'App Lock',
    '앱을 다시 열 때 사용자를 확인합니다.': 'Verify the user when the app is reopened.',
    'PIN 없이 잠금': 'Lock without PIN',
    'PIN 잠금': 'PIN lock',
    '시스템 잠금 비밀번호': 'System authentication',
    '생체인식 잠금 해제': 'Biometric unlock',
    '분류': 'Categories',
    '분류 추가': 'Add category',
    'AI': 'AI',
    'AI 기능': 'AI features',
    '개발 중입니다.': 'In development.',
    'Gemini 사용': 'Use Gemini',
    '민감 문장 AI 차단': 'Block sensitive text from AI',
    '캘린더 데이터 옮기기': 'Import calendar data',
    'Apple 캘린더 또는 Google 캘린더에서 가져옵니다.':
        'Import from Apple Calendar or Google Calendar.',
    'Samsung 캘린더 또는 Google 캘린더에서 가져옵니다.':
        'Import from Samsung Calendar or Google Calendar.',
    '건너뛰기': 'Skip',
    '이전': 'Back',
    '다음': 'Next',
    '일정을 한눈에': 'Your schedule at a glance',
    '월간, 주간, 일간 보기로 필요한 일정에 빠르게 집중하세요.':
        'Focus quickly with month, week, and day views.',
    '기록하고 바로 알림 받기': 'Add events and get reminders',
    '자연스럽게 일정을 기록하고 일정 알림과 아침 브리핑을 받아보세요.':
        'Add events naturally and receive reminders and morning briefings.',
    '중요한 날까지 이어서': 'Stay on track for important days',
    'D-day와 분류를 활용하고 Google Drive로 여러 기기에서 이어서 사용하세요.':
        'Use D-day and categories, and continue across devices with Google Drive.',
    'Daily 시작하기': 'Get Started with Daily',
    'Apple 또는 Google 계정을 연결하거나 계정 없이 로컬로 시작할 수 있습니다.':
        'Connect Apple or Google, or start locally without an account.',
    'Apple로 계속': 'Continue with Apple',
    '로컬로 시작': 'Continue Locally',
    'Google 연결 중': 'Connecting Google',
    'Google로 계속': 'Continue with Google',
    '연결 취소': 'Cancel connection',
    '알림 권한 허용': 'Allow Notifications',
    '검색': 'Search',
    '필터': 'Filter',
    '오늘': 'Today',
    '빠른 보기': 'Quick View',
    '일정 추가': 'Add Event',
    '일정 수정': 'Edit Event',
    '저장': 'Save',
    '취소': 'Cancel',
    '삭제': 'Delete',
    '수정': 'Edit',
    '제목': 'Title',
    '시간': 'Time',
    '장소': 'Location',
    '메모': 'Notes',
    '종일': 'All-day',
    '반복': 'Repeat',
    '없음': 'None',
    '완료': 'Done',
    '지도 바로가기': 'Open in Maps',
    '월간 미니 캘린더': 'Mini Month Calendar',
    '오늘 일정': "Today's Events",
    '일정 없음': 'No events',
    '중요한 날짜': 'Important dates',
    'D-day 일정 없음': 'No D-day events',
    '일정 {count}개': '{count} events',
    'D-day {count}개': '{count} D-day events',
    '공휴일 {count}개': '{count} holidays',
    '검색 닫기': 'Close search',
    '현재 보기에서 검색': 'Search current view',
    'D-day 일정만 보기': 'Show only D-day events',
    '공휴일 표시': 'Show holidays',
    '공휴일 날짜 배경': 'Holiday date background',
    '공휴일 분류 색상을 날짜 배경에 표시합니다.':
        'Use the holiday category color as the date background.',
    '분류 표시': 'Visible categories',
    '검색어 지우기': 'Clear search',
    'AI 입력 닫기': 'Close AI input',
    '일정을 입력하세요': 'Enter an event',
    '등록': 'Add',
    '이 일정으로 등록할까요?': 'Add this event?',
    '열기': 'Open',
    '추가 상세정보가 없습니다.': 'No additional details.',
    '주': 'week',
    '개월': 'month',
    '년': 'year',
    '번': 'time',
    '제목을 입력하세요.': 'Enter a title.',
    '시작일': 'Start date',
    '종료일': 'End date',
    '시작 시간': 'Start time',
    '종료 시간': 'End time',
    '알림 직접 입력': 'Custom reminder',
    '일정 알람': 'Event alarm',
    '종일 일정 알람 시각': 'All-day alarm time',
    'URL / 링크': 'URL / Link',
    '날씨': 'Weather',
    '예: 흐림': 'e.g. Cloudy',
    'D-day 표시': 'Show D-day',
    '달력과 일정 목록에 D-day를 함께 표시합니다.': 'Show D-day in the calendar and event list.',
    '제목, 메모, 장소 검색': 'Search title, notes, or location',
    '검색 결과가 없습니다.': 'No search results.',
    'Apple 연동 해지': 'Disconnect Apple',
    'Google 연동 해지': 'Disconnect Google',
    'D-day 알림': 'D-day reminders',
    'Daily 계정': 'Daily Account',
    'Daily 버전': 'Daily Version',
    'Google Drive 동기화': 'Google Drive Sync',
    'Google Drive에서 복원': 'Restore from Google Drive',
    'Google 계정': 'Google Account',
    'Google 로그인 시 Daily 계정에 연결됩니다.':
        'Signing in with Google links it to your Daily account.',
    '이 계정의 Google Drive AppData에 일정을 백업하고 복원합니다.':
        'Back up and restore events in this account’s Google Drive AppData.',
    'Google 인증 세션이 없습니다. 다시 연결하면 자동 동기화가 재개됩니다.':
        'The Google session is unavailable. Reconnect to resume automatic sync.',
    'Google 로그인 시 Drive AppData 권한도 함께 승인합니다.':
        'Google sign-in also requests access to Drive AppData.',
    '백업': 'Back Up',
    'Google 다시 연결': 'Reconnect Google',
    'Daily 계정 탈퇴': 'Delete Daily Account',
    '로컬 데이터 초기화': 'Reset Local Data',
    'Apple로 로그인됨': 'Signed in with Apple',
    'Apple 로그인': 'Apple Sign-In',
    'Daily 계정에 연결된 Apple 로그인입니다.':
        'This Apple sign-in is linked to your Daily account.',
    'Apple 로그인만으로 Daily를 사용할 수 있습니다.':
        'You can use Daily with Apple sign-in only.',
    'Apple 또는 Google 계정을 연결할 수 있습니다.':
        'You can link an Apple or Google account.',
    '{providers} 로그인 연결됨': '{providers} sign-in linked',
    '아직 동기화 기록이 없습니다.': 'No sync activity yet.',
    '백업 중': 'Backing up',
    '복원 중': 'Restoring',
    '동기화 중': 'Syncing',
    '다른 기기 변경 확인 중': 'Checking changes from other devices',
    '백업 완료': 'Backup complete',
    '복원 완료': 'Restore complete',
    '동기화 완료': 'Sync complete',
    '최신 상태': 'Up to date',
    '일부 백업 보류 · 먼저 복원 필요': 'Some changes are pending · restore first',
    '다른 기기 변경 확인 준비 중': 'Preparing to check changes from other devices',
    '동기화 완료 · 다른 기기 변경 복원':
        'Sync complete · restored changes from another device',
    'PIN 확인': 'Verify PIN',
    '계속': 'Continue',
    '기본 알림 직접 입력': 'Enter default reminder',
    '동기화 상태': 'Sync Status',
    '로그아웃': 'Sign Out',
    '아침 브리핑': 'Morning Briefing',
    '복원': 'Restore',
    '분류 삭제': 'Delete Category',
    '분류 수정': 'Edit Category',
    '사용자 지정 색상': 'Custom Color',
    '시간 선택': 'Choose Time',
    '시간 표시 방식': 'Time Format',
    '시스템 알림 설정 열기': 'Open System Notification Settings',
    '백업 삭제 후 해제': 'Delete backup and disconnect',
    '백업 없이 로그아웃': 'Sign out without backup',
    '백업을 완료하지 못했습니다': 'Backup Could Not Be Completed',
    '버그 제보': 'Report a Bug',
    'Google 로그인 사용자만 GitHub 이슈를 자동 등록할 수 있습니다.':
        'Only users signed in with Google can create a GitHub issue automatically.',
    'Google 로그인이 필요합니다.': 'Google Sign-In Required',
    '확인': 'OK',
    '버그 제보는 Google 로그인으로 Daily를 사용 중인 경우에만 등록할 수 있습니다. 계정 설정에서 Google 계정을 연결해 주세요.':
        'Bug reports are available while using Daily with Google sign-in. Connect your Google account in Account Settings.',
    'Google 계정 이메일 {email}을 제보 연락처로 수집합니다. 이메일은 공개 GitHub 이슈에 표시되지 않고 Daily 서버에 비공개로 저장됩니다.':
        'Your Google account email, {email}, will be collected as the report contact. It will not appear in the public GitHub issue and is stored privately on the Daily server.',
    '작성한 제보 내용은 공개 GitHub 이슈로 등록됩니다. 개인정보를 입력하지 마세요.':
        'Your report content will be posted as a public GitHub issue. Do not enter personal information.',
    '문제 설명': 'Problem Description',
    '재현 방법': 'Steps to Reproduce',
    '예상 동작': 'Expected Behavior',
    '실제 동작': 'Actual Behavior',
    '필수 입력 항목입니다.': 'This field is required.',
    'GitHub 이슈 등록': 'Create GitHub Issue',
    '버그 제보를 등록했습니다.': 'Bug Report Created',
    'GitHub 이슈 #{number}로 등록되었습니다.': 'Created as GitHub issue #{number}.',
    'GitHub에서 보기': 'View on GitHub',
    'Google 로그인 정보를 확인할 수 없습니다.':
        'Google sign-in information could not be verified.',
    '버그 제보 서버에 연결할 수 없습니다.': 'Could not connect to the bug report server.',
    'Google 로그인 상태를 확인한 뒤 다시 시도해 주세요.':
        'Check your Google sign-in status and try again.',
    '버그 제보 요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.':
        'Too many bug reports were submitted. Please try again later.',
    '버그 제보 내용을 다시 확인해 주세요.': 'Review the bug report content and try again.',
    'GitHub 이슈를 생성하지 못했습니다. 잠시 후 다시 시도해 주세요.':
        'Could not create the GitHub issue. Please try again later.',
    '버그 제보 결과를 확인할 수 없습니다.': 'The bug report result could not be verified.',
    '버그 제보를 등록하지 못했습니다. 잠시 후 다시 시도해 주세요.':
        'Could not submit the bug report. Please try again later.',
    '보내기': 'Send',
    '연동 해지': 'Disconnect',
    '연동만 해제': 'Disconnect only',
    '저장 내용 초기화': 'Delete saved data',
    '적용': 'Apply',
    '직접 입력': 'Custom',
    '잠금 방식 변경': 'Change Lock Method',
    '잠금 방식 선택': 'Choose Lock Method',
    '한 자리 지우기': 'Delete one digit',
    '앱 정보': 'App Information',
    '일정이 시작됩니다.': 'The event is starting.',
    '일정 시작 {time}입니다.': 'The event starts {time}.',
    'D-day 일정 알림입니다.': 'This is a D-day event reminder.',
    '오늘의 일정': "Today's Events",
    '오늘 등록된 일정이 없습니다.': 'There are no events today.',
    ' 외 {count}개 더 있습니다.': ' and {count} more.',
    '정시': 'At time of event',
    '{count}분 전': '{count} minutes before',
    '{count}일 전': '{count} days before',
    '{count}시간 전': '{count} hours before',
    '매일 지정한 시간에 오늘 일정을 알려줍니다.':
        "Shows today's events at the selected time each day.",
    'GitHub 제보 양식을 기본 브라우저에서 엽니다.':
        'Open the GitHub report form in your default browser.',
    'GitHub Repository를 열 수 없습니다.': 'Could not open the GitHub repository.',
    '버그 제보 페이지를 열 수 없습니다. 잠시 후 다시 시도하세요.':
        'Could not open the bug report page. Please try again later.',
    '앱 잠금을 해제하려면 PIN을 입력하세요.': 'Enter your PIN to unlock the app.',
    '이 기기에서 시스템 잠금 인증을 사용할 수 없습니다.':
        'System authentication is unavailable on this device.',
    '현재 PIN 없는 잠금 방식에서 변경을 계속할까요?':
        'Continue changing from the current lock-without-PIN method?',
    '기본 일정 알림': 'Default event reminders',
    '몇 분 전에 알릴까요?': 'How many minutes before?',
    '종일 일정 알림 시간': 'All-day reminder time',
    '종일 일정의 알림 기준 시간': 'Default reminder time for all-day events',
    '아침 브리핑 시간': 'Morning briefing time',
    '브리핑을 받을 시간': 'Time to receive the briefing',
    'D-day 알림 직접 입력': 'Custom D-day reminder',
    'D-day 기준 일수. 예: -7, 0': 'Days relative to D-day, e.g. -7, 0',
    '앱 잠금 PIN 설정': 'Set App Lock PIN',
    '잠금 방식': 'Lock method',
    '버전 {version} · 더블 클릭하여 Github 확인하기':
        'Version {version} · Double-click to view GitHub',
    '이름': 'Name',
    '색상': 'Color',
    '"{category}" 분류를 삭제할까요?': 'Delete the “{category}” category?',
    '닫기': 'Close',
    '검색/필터': 'Search / Filter',
    '반복 종료': 'Repeat ends',
    '종료 없음': 'Never',
    '날짜까지': 'On date',
    '횟수만큼': 'After occurrences',
    '반복 간격': 'Repeat interval',
    '몇 {unit}마다 반복할까요?': 'Repeat every how many {unit}?',
    '반복 횟수': 'Number of repeats',
    '몇 회 반복할까요?': 'How many times should it repeat?',
    '제목을 입력해야 일정을 저장할 수 있습니다.': 'Enter a title before saving the event.',
    '종료일은 시작일과 같거나 이후여야 합니다.':
        'The end date must be on or after the start date.',
    '종료 시간은 시작 시간보다 늦어야 합니다.':
        'The end time must be later than the start time.',
    '반복 간격은 1 이상이어야 합니다.': 'The repeat interval must be at least 1.',
    '반복 알람은 추후 루틴 기능에서 사용할 수 있습니다.':
        'Repeating alarms will be available with routines later.',
    '알람 지원 상태를 확인하고 있습니다.': 'Checking alarm support.',
    '이 운영체제에서는 일정 알람을 사용할 수 없습니다.':
        'Event alarms are unavailable on this operating system.',
    '시스템 설정에서 Daily의 알람 권한을 허용해야 합니다.':
        'Allow Daily alarm access in system settings.',
    '0 이상의 숫자를 입력하세요.': 'Enter a number of 0 or greater.',
    '{count} 이상의 숫자를 입력하세요.': 'Enter a number of {count} or greater.',
    '반복 일정 수정': 'Edit Repeating Event',
    '반복 일정 이동': 'Move Repeating Event',
    '이 반복 일정의 어느 범위를 이동할까요?':
        'Which occurrences of this repeating event should be moved?',
    '반복 일정 삭제': 'Delete Repeating Event',
    '일정 삭제': 'Delete Event',
    '"{title}" 일정을 삭제할까요?': 'Delete “{title}”?',
    '이 반복 일정의 어느 범위에 {action}을 적용할까요?':
        'Which occurrences should this {action} apply to?',
    '이 일정만': 'Only This Event',
    '이후 일정': 'This and Future Events',
    '전체 반복': 'All Events',
    '전체 삭제': 'Delete All',
    '일정을 옮기는 중': 'Importing events',
    '{count}개 캘린더 가져오기': 'Import {count} calendars',
    '가져올 수 있는 {provider}가 없습니다.': 'No {provider} calendars are available.',
    '가져오기 완료: {imported}개 추가, {skipped}개 중복 제외, {failed}개 실패':
        'Import complete: {imported} added, {skipped} duplicates skipped, {failed} failed',
    '캘린더 권한 또는 연결 상태를 확인해 주세요.':
        'Check calendar permission or connection status.',
    '가져올 캘린더를 선택해 주세요.': 'Select a calendar to import.',
    '설정에서 Daily의 캘린더 전체 접근을 허용해 주세요.':
        'Allow Daily full calendar access in Settings.',
    '캘린더 접근이 허용되지 않았습니다.': 'Calendar access was not granted.',
    'Google 계정 로그인이 필요합니다.': 'Sign in to a Google account first.',
    'Google Calendar 응답 형식이 올바르지 않습니다.':
        'Google Calendar returned an invalid response.',
    '{title} 불러오기': 'Load {title}',
    '잠금 상태에서는 화면을 볼 수 없습니다.': 'Content is hidden while the app is locked.',
    '잠금 상태입니다.': 'Locked',
    'PIN 입력': 'Enter PIN',
    '비밀번호를 통해 잠금해제': 'Unlock with PIN',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 확인합니다.':
        'Verify with Face ID, Touch ID, or the device password.',
    '시스템 잠금으로 해제': 'Unlock with System Authentication',
    'PIN을 계속 입력하거나 지워서 다시 입력하세요.':
        'Continue entering the PIN, or clear it and try again.',
    'PIN이 일치하지 않습니다.': 'The PIN does not match.',
    'Daily 잠금을 해제하려면 인증이 필요합니다.': 'Authentication is required to unlock Daily.',
    '시스템 인증을 완료하지 못했습니다.': 'System authentication was not completed.',
    'Touch ID 또는 Apple Watch로 Daily PIN 잠금을 해제합니다.':
        'Unlock Daily PIN lock with Touch ID or Apple Watch.',
    'Daily PIN 잠금을 생체인식으로 해제합니다.': 'Unlock Daily PIN lock with biometrics.',
    '생체인식을 완료하지 못했습니다. PIN을 입력해 주세요.':
        'Biometric authentication was not completed. Enter your PIN.',
    '일정이 없습니다.': 'No events.',
    '시작 시각 · 중지 또는 10분 후 다시 알림': 'Start time · Stop or snooze for 10 minutes',
    '{time} · 중지 또는 10분 후 다시 알림': '{time} · Stop or snooze for 10 minutes',
    'Apple 로그인 창을 여는 중입니다.': 'Opening Apple sign-in.',
    'Apple 로그인이 취소되었습니다.': 'Apple sign-in was canceled.',
    'Apple 로그인이 완료되었습니다.': 'Apple sign-in completed.',
    'Apple 로그인이 완료되었습니다. 연결된 Google Drive 동기화를 복원했습니다.':
        'Apple sign-in completed. The linked Google Drive sync was restored.',
    'Apple 연동을 해지했습니다.': 'Apple was disconnected.',
    'Google 로그인 창을 여는 중입니다.': 'Opening Google sign-in.',
    'Google Drive 연결이 취소되었습니다. 다시 연결할 수 있습니다.':
        'Google Drive connection was canceled. You can connect again.',
    '알림 권한 요청을 여는 중입니다.': 'Opening the notification permission request.',
    '알림 권한 설정을 확인했습니다.': 'Notification permission settings checked.',
    '앱을 벗어난 동안 화면만 가리고 복귀하면 자동으로 해제합니다.':
        'Hide content while away and unlock automatically when you return.',
    'Daily 전용 PIN으로 잠그며 생체인식을 선택해서 함께 사용할 수 있습니다.':
        'Lock with a Daily PIN and optionally use biometrics.',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 인증합니다.':
        'Authenticate with Face ID, Touch ID, or the device password.',
    '시스템 알림 설정을 열 수 없습니다. OS 설정에서 Daily 알림을 허용하세요.':
        'Could not open notification settings. Allow Daily notifications in system settings.',
    'Gemini API 키': 'Gemini API Key',
    'Android에서는 시스템 설정 > 앱 > Daily > 알림에서 허용을 켜세요.':
        'On Android, enable notifications in Settings > Apps > Daily > Notifications.',
    '종일 일정은 설정의 종일 알림 시간을 기준으로 예약됩니다.':
        'All-day events use the all-day reminder time from Settings.',
    '켜면 macOS 알림 권한을 요청하고 시작 시각에 시스템 알림을 전달합니다.':
        'Requests macOS notification permission and sends a system notification at the start time.',
    '켜면 시스템 알람 권한을 요청하고 정시 알림을 알람으로 대체합니다.':
        'Requests alarm permission and replaces the start-time notification with an alarm.',
    '선택한 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        'Sends a macOS system notification with sound and snooze at the selected time.',
    '시작 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        'Sends a macOS system notification with sound and snooze at the start time.',
    '선택한 시각에 시스템 알람이 울립니다.': 'A system alarm sounds at the selected time.',
    '시작 시각의 정시 알림을 시스템 알람으로 대체합니다.':
        'Replaces the start-time notification with a system alarm.',
    'Google Drive 연결이 완료되었습니다.': 'Google Drive connected.',
    'Google Drive 복원 완료': 'Google Drive restore completed',
    '요청을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.':
        'The request could not be completed. Try again shortly.',
    '네트워크 연결을 확인한 뒤 다시 시도해 주세요.':
        'Check your network connection and try again.',
    'Google Drive 연결이 만료되었습니다. 다시 연결해 주세요.':
        'The Google Drive connection expired. Connect again.',
    'Google Drive 권한이 부족합니다. 다시 연결해 권한을 승인해 주세요.':
        'Google Drive permission is insufficient. Reconnect and approve access.',
    'Google Drive 요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.':
        'Too many Google Drive requests. Try again shortly.',
    'Google Drive 서버 응답이 불안정합니다. 잠시 후 다시 시도해 주세요.':
        'Google Drive is temporarily unstable. Try again shortly.',
    'PIN 없음': 'No PIN',
    '시스템': 'System',
    '즉시 알림을 보내고 예약 상태를 확인합니다.':
        'Send a notification now and check scheduled status.',
    'PIN은 4자리 이상이어야 합니다.': 'PIN must contain at least 4 digits.',
    'PIN이 일치하지 않습니다. 다시 입력하세요.': 'PINs do not match. Try again.',
    '마지막 성공: {time}': 'Last success: {time}',
    '새 일정에 알림을 자동으로 추가하지 않습니다.':
        'Do not add reminders automatically to new events.',
    'Apple 캘린더': 'Apple Calendar',
    'Samsung 캘린더': 'Samsung Calendar',
    'Google 캘린더': 'Google Calendar',
    '공휴일': 'Holidays',
    '신정': "New Year's Day",
    '삼일절': 'March 1st Movement Day',
    '노동절': 'Labor Day',
    '어린이날': "Children's Day",
    '현충일': 'Memorial Day',
    '제헌절': 'Constitution Day',
    '광복절': 'Liberation Day',
    '개천절': 'National Foundation Day',
    '한글날': 'Hangeul Day',
    '기독탄신일': 'Christmas Day',
    '설날 연휴': 'Seollal Holiday',
    '설날': 'Seollal',
    '부처님 오신 날': "Buddha's Birthday",
    '추석 연휴': 'Chuseok Holiday',
    '추석': 'Chuseok',
    '대체공휴일': 'Substitute Holiday',
    '반복 없음': 'Does not repeat',
    '매일': 'Daily',
    '매주': 'Weekly',
    '매월': 'Monthly',
    '매년': 'Yearly',
    '반복 종료일': 'Repeat end date',
    '{count}회': '{count} times',
    '{count}일마다': 'Every {count} day(s)',
    '{count}주마다': 'Every {count} week(s)',
    '{count}개월마다': 'Every {count} month(s)',
    '{count}년마다': 'Every {count} year(s)',
    '{count}번마다': 'Every {count} time(s)',
    'AI 설정': 'AI Settings',
    'Daily 개선 참여': 'Help Improve Daily',
    'Daily 계정의 Apple/Google 연결 및 병합 정보, Google Drive AppData 백업, 이 기기의 모든 일정과 설정을 삭제하고 시작 화면으로 돌아갑니다. 향후 iCloud 저장 데이터도 이 경로에서 함께 삭제됩니다. 이 작업은 되돌릴 수 없습니다.':
        'Delete the Daily account connections and merge information for Apple and Google, the Google Drive AppData backup, and all events and settings on this device, then return to the start screen. Future iCloud data will also be deleted here. This action cannot be undone.',
    'Daily를 어떻게\n시작할까요?': 'How would you like to\nstart Daily?',
    'Daily의 AI 기능 준비 상태를 확인합니다.': 'Check the readiness of Daily AI features.',
    'Google Drive AppData의 일정과 설정을 이 기기에 복원할까요? 이 기기의 더 최신이거나 아직 백업되지 않은 변경은 유지됩니다.':
        'Restore events and settings from Google Drive AppData to this device? Newer or not-yet-backed-up changes on this device will be kept.',
    'Google 계정 연결을 해제할까요? Google Drive AppData 백업은 유지하거나 함께 삭제할 수 있습니다. 로컬 일정과 설정은 유지됩니다.':
        'Disconnect the Google account? You can keep or delete the Google Drive AppData backup. Local events and settings will remain.',
    'Google 연결은 앱 전용 Drive AppData 백업과 동기화에만 사용하며 일반 Drive 파일은 읽거나 수정하지 않습니다.':
        'Google access is used only for app-specific Drive AppData backup and sync. Daily does not read or modify regular Drive files.',
    'Siri 단축어 추가하기': 'Add Siri Shortcut',
    'Siri 또는 단축어로 Daily 작업을 실행하면 날짜별 기록이 여기에 표시됩니다.':
        'Daily actions run through Siri or Shortcuts will appear here by date.',
    'Siri와 Daily': 'Siri and Daily',
    '{month} · 일정 {count}개': '{month} · {count} events',
    '가져올 캘린더를 선택하면 일정과 기존 분류 색상을 Daily에 복사합니다.':
        'Select calendars to copy their events and existing category colors into Daily.',
    '개인정보 및 잠금': 'Privacy & Lock',
    '개인정보 및 지원': 'Privacy & Support',
    '계정을 연결하면 기기 간 동기화를 사용할 수 있고, 계정 없이 이 기기에서만 시작할 수도 있어요.':
        'Connect an account to sync across devices, or start without an account on this device only.',
    '권한 설정을 완료하지 못했습니다. 나중에 설정에서 다시 시도할 수 있습니다. ({error})':
        'Could not complete permission setup. You can try again later in Settings. ({error})',
    '권한은 나중에 설정에서 다시 요청하거나 변경할 수 있습니다.':
        'You can request or change permissions later in Settings.',
    '기록부터 완료까지': 'From capture to completion',
    '나중에': 'Later',
    '더 완벽한 Daily를\n함께 만들어요.': 'Help us make Daily\neven better.',
    '동의해주시면 실제 사용 흐름과 성능 문제를 익명으로 분석해 더 빠르고 안정적인 Daily를 만들 수 있어요.':
        'With your consent, anonymous usage flow and performance data help us make Daily faster and more reliable.',
    '마지막 단계': 'Final step',
    '말 한마디로\n일정을 관리하세요.': 'Manage your schedule\nwith your voice.',
    '백업할 변경 사항이 없습니다.': 'There are no changes to back up.',
    '버전 정보, GitHub와 버그 제보를 확인합니다.':
        'View version information, GitHub, and bug reporting.',
    '분류 설정': 'Category Settings',
    '사용 흐름': 'Usage flow',
    '색상, 표시 여부와 일정 정렬 순서를 관리합니다.':
        'Manage colors, visibility, and event sorting order.',
    '선택을 저장하지 못했습니다. 다시 시도해 주세요.':
        'Could not save your choice. Please try again.',
    '성능 개선': 'Performance improvement',
    '시그널 단축어를 추가하면 Siri에게 일정을 묻거나 추가하고 수정할 수 있어요.':
        'Add the Signal shortcut to ask Siri about events or to add and edit them.',
    '시작 전 알림과 브리핑': 'Reminders and briefing before you start',
    '실행': 'Run',
    '아직 Google Drive에 백업되지 않은 변경이 있을 수 있습니다. 그래도 이 기기의 데이터를 삭제하고 로그아웃할까요?':
        'Some changes may not be backed up to Google Drive yet. Delete data on this device and sign out anyway?',
    '알림 및 알람 허용': 'Allow Notifications and Alarms',
    '알림과 알람을\n준비할까요?': 'Set up notifications\nand alarms?',
    '앱 정보 및 지원': 'App Info & Support',
    '언어, 테마, 글자 크기와 달력 표시 방식을 설정합니다.':
        'Set language, theme, text size, and calendar display options.',
    '연락처 보호': 'Contact privacy',
    '예: “Siri야, Daily에서 시그널 실행.”이라고 말한 뒤 “내일 오전 9시에 헬스장 일정 추가해줘.”라고 이어서 말하세요.':
        'For example, say “Siri, run Signal in Daily,” then say “Add a gym event tomorrow at 9 AM.”',
    '오늘을 더\n가볍게 정리하세요.': 'Make today\neasier to manage.',
    '오류 범주와 응답 시간': 'Error categories and response time',
    '월간, 주간, 일간 보기': 'Month, week, and day views',
    '이 기기의 모든 일정과 설정을 삭제하고 시작 화면으로 돌아갑니다.':
        'Delete all events and settings on this device, then return to the start screen.',
    '이 기기의 일정, 설정, 로그인 정보를 삭제하고 시작 화면으로 돌아갑니다. Google Drive AppData의 백업은 삭제하지 않습니다.':
        'Delete events, settings, and sign-in information on this device, then return to the start screen. The Google Drive AppData backup will remain.',
    '익명 분석 데이터와 앱 잠금을 관리합니다.': 'Manage anonymous analytics data and app lock.',
    '익명 분석 허용': 'Allow Anonymous Analytics',
    '일정 내용, 검색어, 계정 정보, 위치, 광고 식별자는 수집하지 않습니다. 언제든 설정에서 변경할 수 있어요.':
        'Daily does not collect event content, search terms, account information, location, or advertising identifiers. You can change this anytime in Settings.',
    '일정 알림': 'Event reminders',
    '일정 알림과 아침 브리핑을 받으려면 알림 권한이 필요합니다. 지원되는 기기에서는 일정별 알람도 사용할 수 있어요.':
        'Notification permission is required for event reminders and morning briefings. Event alarms are also available on supported devices.',
    '일정과 할 일': 'Events and to-dos',
    '일정과 할 일을 한곳에서 보고, 필요한 순간에만 알림을 받으세요.':
        'See events and to-dos in one place and get notified only when needed.',
    '일정을 불러오지 못했습니다. ({error})': 'Could not load events. ({error})',
    '지원 기기에서 선택 사용': 'Optional on supported devices',
    '표시 옵션': 'Display Options',
    '필요한 순간 놓치지 않기': 'Never miss what matters',
    '한눈에 보는 일정': 'Your schedule at a glance',
    '화면 및 달력': 'Display & Calendar',
    '화면 및 일정': 'Display & Schedule',
    '화면과 기능 사용': 'Screens and feature usage',
  },
  'ja': {
    '업데이트 중입니다': 'Dailyを更新しています',
    '업데이트 확인 중': '更新を確認しています',
    '최신 백업을 복원하고 있습니다.': '最新のバックアップを復元しています。',
    '안전 스냅샷을 만들고 있습니다.': '安全なスナップショットを作成しています。',
    '일정을 Todo 형식으로 업데이트하고 있습니다.': '予定をTodo形式に更新しています。',
    '업데이트 결과를 확인하고 있습니다.': '更新結果を確認しています。',
    '업데이트된 일정을 백업하고 있습니다.': '更新した予定をバックアップしています。',
    '업데이트가 완료되었습니다.': '更新が完了しました。',
    '업데이트를 완료하지 못했습니다': '更新を完了できませんでした',
    '다시 시도': '再試行',
    '시스템 설정에 따름': 'システム設定に従う',
    '언어': '言語',
    '설정': '設定',
    '알림 설정': '通知設定',
    '계정 설정': 'アカウント設定',
    '알림': '通知',
    '계정': 'アカウント',
    'Siri 단축어 설정': 'Siriショートカット設定',
    '자동 등록된 시그널 단축어와 사용 방법을 확인합니다.': '自動登録されたSignalショートカットと使い方を確認します。',
    '시그널 단축어 사용': 'Signalショートカットを使う',
    '시그널은 앱 설치와 함께 자동으로 등록되므로 직접 만들 필요가 없습니다.':
        'Signalはアプリと一緒に自動登録されるため、自分で作成する必要はありません。',
    '1. Siri에게 “Daily에서 시그널 실행”이라고 말합니다.': '1. Siriに「DailyでSignalを実行」と話しかけます。',
    '2. Siri가 질문하면 원하는 일정 명령을 이어서 말합니다.': '2. Siriが尋ねたら、実行したい予定の操作を続けて話します。',
    '예: “내일 오전 9시에 헬스장 일정을 추가해줘.”': '例：「明日の午前9時にジムの予定を追加して。」',
    '단축어 앱에서 Daily의 Signal App Shortcut이 등록되었는지 확인할 수 있습니다.':
        'ショートカットAppでDailyのSignal App Shortcutを確認できます。',
    '단축어 앱에서 확인': 'ショートカットAppで確認',
    '일정을 놓을 날짜': '移動先の日付',
    '시그널 단축어를 추가하고 Siri에서 Daily 명령을 사용합니다.':
        'Signalショートカットを追加して、SiriからDailyの操作を使います。',
    '시그널 단축어 추가 화면을 열 수 없습니다.': 'Signalショートカットの追加画面を開けませんでした。',
    '시그널 단축어 추가': 'Signalショートカットを追加',
    '단축어 앱에서 다음 순서로 구성하세요.': 'ショートカットAppで次の順に設定してください。',
    '1. 새 단축어를 만들고 이름을 시그널로 지정합니다.': '1. 新しいショートカットを作成し、名前を「Signal」にします。',
    '2. 텍스트 받아쓰기 동작을 추가합니다.': '2. 「テキストを音声入力」アクションを追加します。',
    '3. Daily Signal 동작을 추가하고 받아쓰기한 텍스트를 Signal phrase에 연결합니다.':
        '3. 「Daily Signal」を追加し、音声入力したテキストをSignal phraseに接続します。',
    '단축어 생성 화면 열기': 'ショートカット作成画面を開く',
    '단축어 앱을 열 수 없습니다.': 'ショートカットAppを開けませんでした。',
    'Siri 작업 기록': 'Siriアクティビティ',
    'Siri 작업 상세': 'Siri操作の詳細',
    '작업': '操作',
    '상태': '状態',
    '실행 시각': '実行日時',
    '요약': '概要',
    '결과': '結果',
    '시작': '開始',
    '종료': '終了',
    '종일 일정': '終日予定',
    '예': 'はい',
    '아니요': 'いいえ',
    '기록 전체 삭제': 'すべての履歴を削除',
    'Siri 작업 기록 삭제': 'Siriアクティビティを削除',
    '저장된 Siri 작업 기록을 모두 삭제하시겠습니까?': '保存されたSiriアクティビティをすべて削除しますか？',
    '성공': '成功',
    '실패': '失敗',
    'Siri와 자동화로 실행한 Daily 작업을 날짜별로 확인합니다.':
        'Siriとオートメーションで実行したDailyの操作を日付別に確認します。',
    '날짜 선택': '日付を選択',
    '전체 날짜 보기': 'すべての日付を表示',
    '기록된 Siri 작업이 없습니다.': 'Siriの操作履歴はありません。',
    '오늘 일정 조회': '今日の予定',
    '내일 일정 조회': '明日の予定',
    '날짜별 일정 조회': '日付別の予定',
    '다음 일정 조회': '次の予定',
    'D-day 조회': 'D-day予定',
    '달력 열기': 'カレンダーを開く',
    'Siri 작업': 'Siri操作',
    '지금 듣는 중...': '聞き取り中...',
    '시그널 처리 중...': 'シグナルを処理中...',
    '다시 말씀해 주세요': 'もう一度お話しください',
    '필요한 정보를 이어서 말씀해 주세요.': '不足している情報を続けてお話しください。',
    '음성 명령을 처리하지 못했습니다.': '音声コマンドを処理できませんでした。',
    '듣기 중지': '聞き取りを停止',
    '다시 듣기': 'もう一度聞く',
    '음성 듣기가 중단되었습니다.': '聞き取りが中断されました。',
    '이 명령을 실행할까요?': 'このコマンドを実行しますか？',
    '인증 또는 작업이 취소되었습니다.': '認証または操作がキャンセルされました。',
    '기기 인증을 완료하지 못했습니다.': 'デバイス認証を完了できませんでした。',
    '작업을 취소했습니다.': '操作をキャンセルしました。',
    '일정은 저장했지만 알림 또는 동기화 처리가 보류되었습니다.': '予定は保存されましたが、通知または同期処理は保留中です。',
    '일정은 저장했으며 클라우드 동기화는 연결 후 재시도됩니다.': '予定は保存されました。クラウド同期はアカウント接続後に再試行されます。',
    '실행 확인': '実行の確認',
    '듣기 완료': '聞き取りを完了',
    '텍스트로 입력': 'テキストで入力',
    'Daily에 요청할 내용을 입력하세요.': 'Dailyへのリクエストを入力してください。',
    '화면': '画面',
    '테마': 'テーマ',
    '자동': '自動',
    '화이트': 'ライト',
    '다크': 'ダーク',
    '달력': 'カレンダー',
    '주 시작 요일': '週の開始曜日',
    '일': '日',
    '월': '月',
    '주 보기': '週',
    '월 보기': '月',
    '일 보기': '日',
    '음력 표시': '旧暦を表示',
    '인접한 달 날짜 표시': '隣接月の日付を表示',
    '월간 이동 방식': '月表示の移動方法',
    '좌우 슬라이드': '左右スワイプ',
    '상하 스크롤': '上下スクロール',
    '첫 화면': '起動画面',
    '앱을 열었을 때 먼저 보여줄 화면': 'アプリ起動時に最初に表示する画面',
    '기본 보기': 'デフォルト表示',
    '주간·일간 표시 방식': '週・日表示方式',
    '목록': 'リスト',
    '스케줄': 'スケジュール',
    '종일 일정 표시': '終日予定を表示',
    '종일 일정 숨기기': '終日予定を非表示',
    '주간': '週',
    '월간': '月',
    '일간': '日',
    '전체 UI 글자 크기': 'UI文字サイズ',
    '기본': '標準',
    '가운데': '中央',
    '일정 제목 정렬': '予定タイトルの配置',
    '일정 정렬 우선순위': '予定の並び順',
    '분류 우선': 'カテゴリ優先',
    '시간 우선': '時間優先',
    '길게 눌러 순서 변경': '長押しして並べ替え',
    '크게': '大',
    '더 크게': '特大',
    '개인정보': 'プライバシー',
    '익명 사용성 분석 허용': '匿名の利用状況分析を許可',
    '일정 내용, 검색어, 계정 정보 없이 화면과 기능 사용, 오류 범주, 성능 정보만 수집합니다.':
        '予定内容、検索語、アカウント情報を含めず、画面・機能の利用、エラー分類、性能情報のみを収集します。',
    '분석 데이터 삭제': '分析データを削除',
    '이 기기에 전송 대기 중인 익명 분석 데이터를 삭제합니다.': 'このデバイスで送信待ちの匿名分析データを削除します。',
    '이 기기에 전송 대기 중인 익명 분석 데이터를 삭제할까요? 이미 전송되어 집계된 데이터는 계정이나 기기와 연결되지 않아 특정 사용자를 식별하거나 되돌릴 수 없습니다.':
        'このデバイスで送信待ちの匿名分析データを削除しますか？送信済みデータはアカウントやデバイスに結び付けず集計されるため、特定ユーザーの識別や復元はできません。',
    '전송 대기 분석 데이터를 삭제했습니다.': '送信待ちの分析データを削除しました。',
    '앱 잠금': 'アプリロック',
    'PIN 없이 잠금': 'PINなしロック',
    'PIN 잠금': 'PINロック',
    '시스템 잠금 비밀번호': 'システム認証',
    '생체인식 잠금 해제': '生体認証でロック解除',
    '분류': 'カテゴリ',
    '분류 추가': 'カテゴリを追加',
    'AI 기능': 'AI機能',
    '개발 중입니다.': '開発中です。',
    '캘린더 데이터 옮기기': 'カレンダーデータを読み込む',
    '건너뛰기': 'スキップ',
    '이전': '戻る',
    '다음': '次へ',
    '일정을 한눈에': '予定をひと目で',
    '기록하고 바로 알림 받기': '記録してすぐ通知',
    '중요한 날까지 이어서': '大切な日までしっかり管理',
    'Daily 시작하기': 'Dailyを始める',
    'Apple로 계속': 'Appleで続ける',
    '로컬로 시작': 'ローカルで始める',
    'Google 연결 중': 'Googleに接続中',
    'Google로 계속': 'Googleで続ける',
    '연결 취소': '接続をキャンセル',
    '알림 권한 허용': '通知を許可',
    '검색': '検索',
    '필터': 'フィルタ',
    '오늘': '今日',
    '빠른 보기': 'クイック表示',
    '일정 추가': '予定を追加',
    '일정 수정': '予定を編集',
    '저장': '保存',
    '취소': 'キャンセル',
    '삭제': '削除',
    '수정': '編集',
    '제목': 'タイトル',
    '시간': '時刻',
    '장소': '場所',
    '메모': 'メモ',
    '종일': '終日',
    '반복': '繰り返し',
    '없음': 'なし',
    '완료': '完了',
    '지도 바로가기': '地図で開く',
    '월간 미니 캘린더': '月間ミニカレンダー',
    '오늘 일정': '今日の予定',
    '일정 없음': '予定なし',
    '중요한 날짜': '重要な日',
    'D-day 일정 없음': 'D-day予定なし',
    '일정 {count}개': '予定{count}件',
    'D-day {count}개': 'D-day {count}件',
    '공휴일 {count}개': '祝日{count}件',
    '검색 닫기': '検索を閉じる',
    '현재 보기에서 검색': '現在の表示を検索',
    'D-day 일정만 보기': 'D-day予定のみ表示',
    '공휴일 표시': '祝日を表示',
    '공휴일 날짜 배경': '祝日の背景',
    '공휴일 분류 색상을 날짜 배경에 표시합니다.': '祝日カテゴリの色を日付の背景に表示します。',
    '분류 표시': '表示するカテゴリ',
    '검색어 지우기': '検索語を消去',
    'AI 입력 닫기': 'AI入力を閉じる',
    '일정을 입력하세요': '予定を入力してください',
    '등록': '登録',
    '이 일정으로 등록할까요?': 'この予定を登録しますか？',
    '열기': '開く',
    '추가 상세정보가 없습니다.': '追加情報はありません。',
    '주': '週',
    '개월': 'か月',
    '년': '年',
    '번': '回',
    '제목을 입력하세요.': 'タイトルを入力してください。',
    '시작일': '開始日',
    '종료일': '終了日',
    '시작 시간': '開始時刻',
    '종료 시간': '終了時刻',
    '알림 직접 입력': '通知を直接入力',
    '일정 알람': '予定アラーム',
    '종일 일정 알람 시각': '終日予定のアラーム時刻',
    'URL / 링크': 'URL / リンク',
    '날씨': '天気',
    '예: 흐림': '例：曇り',
    'D-day 표시': 'D-dayを表示',
    '제목, 메모, 장소 검색': 'タイトル、メモ、場所を検索',
    '검색 결과가 없습니다.': '検索結果がありません。',
    'Apple 연동 해지': 'Apple連携を解除',
    'Google 연동 해지': 'Google連携を解除',
    'D-day 알림': 'D-day通知',
    'Daily 계정': 'Dailyアカウント',
    'Daily 버전': 'Dailyバージョン',
    'Google Drive 동기화': 'Google Drive同期',
    'Google Drive에서 복원': 'Google Driveから復元',
    'Google 계정': 'Googleアカウント',
    'Google 로그인 시 Daily 계정에 연결됩니다.': 'GoogleでログインするとDailyアカウントに連携されます。',
    '이 계정의 Google Drive AppData에 일정을 백업하고 복원합니다.':
        'このアカウントのGoogle Drive AppDataに予定をバックアップし、復元します。',
    'Google 인증 세션이 없습니다. 다시 연결하면 자동 동기화가 재개됩니다.':
        'Google認証セッションがありません。再接続すると自動同期が再開します。',
    'Google 로그인 시 Drive AppData 권한도 함께 승인합니다.':
        'Googleログイン時にDrive AppDataへのアクセスも許可します。',
    '백업': 'バックアップ',
    'Google 다시 연결': 'Googleに再接続',
    'Daily 계정 탈퇴': 'Dailyアカウントを削除',
    '로컬 데이터 초기화': 'ローカルデータを初期化',
    'Apple로 로그인됨': 'Appleでログイン済み',
    'Apple 로그인': 'Appleログイン',
    'Daily 계정에 연결된 Apple 로그인입니다.': 'Dailyアカウントに連携されたAppleログインです。',
    'Apple 로그인만으로 Daily를 사용할 수 있습니다.': 'AppleログインだけでDailyを利用できます。',
    'Apple 또는 Google 계정을 연결할 수 있습니다.': 'AppleまたはGoogleアカウントを連携できます。',
    '{providers} 로그인 연결됨': '{providers}ログイン連携済み',
    '아직 동기화 기록이 없습니다.': '同期履歴はまだありません。',
    '백업 중': 'バックアップ中',
    '복원 중': '復元中',
    '동기화 중': '同期中',
    '다른 기기 변경 확인 중': 'ほかのデバイスの変更を確認中',
    '백업 완료': 'バックアップ完了',
    '복원 완료': '復元完了',
    '동기화 완료': '同期完了',
    '최신 상태': '最新の状態',
    '일부 백업 보류 · 먼저 복원 필요': '一部保留中・先に復元が必要',
    '다른 기기 변경 확인 준비 중': 'ほかのデバイスの変更確認を準備中',
    '동기화 완료 · 다른 기기 변경 복원': '同期完了・ほかのデバイスの変更を復元',
    'PIN 확인': 'PIN確認',
    '계속': '続ける',
    '기본 알림 직접 입력': 'デフォルト通知を入力',
    '동기화 상태': '同期状態',
    '로그아웃': 'ログアウト',
    '아침 브리핑': '朝のブリーフィング',
    '복원': '復元',
    '분류 삭제': 'カテゴリを削除',
    '분류 수정': 'カテゴリを編集',
    '사용자 지정 색상': 'カスタムカラー',
    '시간 선택': '時刻を選択',
    '시간 표시 방식': '時刻表示形式',
    '시스템 알림 설정 열기': 'システム通知設定を開く',
    '백업 삭제 후 해제': 'バックアップを削除して解除',
    '백업 없이 로그아웃': 'バックアップせずログアウト',
    '백업을 완료하지 못했습니다': 'バックアップを完了できませんでした',
    '버그 제보': '不具合を報告',
    'Google 로그인 사용자만 GitHub 이슈를 자동 등록할 수 있습니다.':
        'Googleでログイン中のユーザーのみ、GitHub Issueを自動登録できます。',
    'Google 로그인이 필요합니다.': 'Googleログインが必要です',
    '확인': 'OK',
    '버그 제보는 Google 로그인으로 Daily를 사용 중인 경우에만 등록할 수 있습니다. 계정 설정에서 Google 계정을 연결해 주세요.':
        '不具合報告はGoogleログインでDailyを使用中の場合のみ登録できます。アカウント設定でGoogleアカウントを連携してください。',
    'Google 계정 이메일 {email}을 제보 연락처로 수집합니다. 이메일은 공개 GitHub 이슈에 표시되지 않고 Daily 서버에 비공개로 저장됩니다.':
        'Googleアカウントのメールアドレス（{email}）を連絡先として収集します。公開GitHub Issueには表示せず、Dailyサーバーに非公開で保存します。',
    '작성한 제보 내용은 공개 GitHub 이슈로 등록됩니다. 개인정보를 입력하지 마세요.':
        '入力した報告内容は公開GitHub Issueとして登録されます。個人情報を入力しないでください。',
    '문제 설명': '問題の説明',
    '재현 방법': '再現手順',
    '예상 동작': '期待する動作',
    '실제 동작': '実際の動作',
    '필수 입력 항목입니다.': '必須項目です。',
    'GitHub 이슈 등록': 'GitHub Issueを登録',
    '버그 제보를 등록했습니다.': '不具合報告を登録しました',
    'GitHub 이슈 #{number}로 등록되었습니다.': 'GitHub Issue #{number}として登録されました。',
    'GitHub에서 보기': 'GitHubで表示',
    'Google 로그인 정보를 확인할 수 없습니다.': 'Googleログイン情報を確認できません。',
    '버그 제보 서버에 연결할 수 없습니다.': '不具合報告サーバーに接続できません。',
    'Google 로그인 상태를 확인한 뒤 다시 시도해 주세요.': 'Googleログイン状態を確認してから再試行してください。',
    '버그 제보 요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.':
        '不具合報告のリクエストが多すぎます。しばらくしてから再試行してください。',
    '버그 제보 내용을 다시 확인해 주세요.': '不具合報告の内容を確認してください。',
    'GitHub 이슈를 생성하지 못했습니다. 잠시 후 다시 시도해 주세요.':
        'GitHub Issueを作成できませんでした。しばらくしてから再試行してください。',
    '버그 제보 결과를 확인할 수 없습니다.': '不具合報告の結果を確認できません。',
    '버그 제보를 등록하지 못했습니다. 잠시 후 다시 시도해 주세요.':
        '不具合報告を登録できませんでした。しばらくしてから再試行してください。',
    '보내기': '送信',
    '연동 해지': '連携解除',
    '연동만 해제': '連携のみ解除',
    '저장 내용 초기화': '保存内容を削除',
    '적용': '適用',
    '직접 입력': 'カスタム',
    '잠금 방식 변경': 'ロック方式を変更',
    '잠금 방식 선택': 'ロック方式を選択',
    '한 자리 지우기': '1桁削除',
    '앱 정보': 'アプリ情報',
    '일정이 시작됩니다.': '予定が始まります。',
    '일정 시작 {time}입니다.': '予定開始の{time}です。',
    'D-day 일정 알림입니다.': 'D-day予定のお知らせです。',
    '오늘의 일정': '今日の予定',
    '오늘 등록된 일정이 없습니다.': '今日の予定はありません。',
    ' 외 {count}개 더 있습니다.': '、ほか{count}件',
    '정시': '予定時刻',
    '{count}분 전': '{count}分前',
    '{count}일 전': '{count}日前',
    '{count}시간 전': '{count}時間前',
    '앱 잠금을 해제하려면 PIN을 입력하세요.': 'アプリのロック解除用PINを入力してください。',
    '이 기기에서 시스템 잠금 인증을 사용할 수 없습니다.': 'このデバイスではシステム認証を利用できません。',
    '기본 일정 알림': '予定のデフォルト通知',
    '몇 분 전에 알릴까요?': '何分前に通知しますか？',
    '종일 일정 알림 시간': '終日予定の通知時刻',
    '종일 일정의 알림 기준 시간': '終日予定の基準通知時刻',
    '아침 브리핑 시간': '朝のブリーフィング時刻',
    '브리핑을 받을 시간': 'ブリーフィングを受け取る時刻',
    'D-day 알림 직접 입력': 'D-day通知を直接入力',
    'D-day 기준 일수. 예: -7, 0': 'D-day基準の日数。例：-7、0',
    '앱 잠금 PIN 설정': 'アプリロックPINを設定',
    '잠금 방식': 'ロック方式',
    '버전 {version} · 더블 클릭하여 Github 확인하기': 'バージョン{version}・ダブルクリックでGitHubを表示',
    '이름': '名前',
    '색상': '色',
    '"{category}" 분류를 삭제할까요?': '「{category}」カテゴリを削除しますか？',
    '닫기': '閉じる',
    '검색/필터': '検索／フィルタ',
    '반복 종료': '繰り返し終了',
    '종료 없음': '終了なし',
    '날짜까지': '指定日まで',
    '횟수만큼': '回数を指定',
    '반복 간격': '繰り返し間隔',
    '몇 {unit}마다 반복할까요?': '何{unit}ごとに繰り返しますか？',
    '반복 횟수': '繰り返し回数',
    '몇 회 반복할까요?': '何回繰り返しますか？',
    '제목을 입력해야 일정을 저장할 수 있습니다.': '予定を保存するにはタイトルを入力してください。',
    '종료일은 시작일과 같거나 이후여야 합니다.': '終了日は開始日以降にしてください。',
    '종료 시간은 시작 시간보다 늦어야 합니다.': '終了時刻は開始時刻より後にしてください。',
    '반복 간격은 1 이상이어야 합니다.': '繰り返し間隔は1以上にしてください。',
    '반복 알람은 추후 루틴 기능에서 사용할 수 있습니다.': '繰り返しアラームは今後ルーティン機能で利用できます。',
    '알람 지원 상태를 확인하고 있습니다.': 'アラーム対応状況を確認しています。',
    '이 운영체제에서는 일정 알람을 사용할 수 없습니다.': 'このOSでは予定アラームを利用できません。',
    '시스템 설정에서 Daily의 알람 권한을 허용해야 합니다.': 'システム設定でDailyのアラーム権限を許可してください。',
    '반복 일정 수정': '繰り返し予定を編集',
    '반복 일정 이동': '繰り返し予定を移動',
    '이 반복 일정의 어느 범위를 이동할까요?': 'この繰り返し予定のどの範囲を移動しますか？',
    '반복 일정 삭제': '繰り返し予定を削除',
    '일정 삭제': '予定を削除',
    '"{title}" 일정을 삭제할까요?': '「{title}」を削除しますか？',
    '이 반복 일정의 어느 범위에 {action}을 적용할까요?': 'この繰り返し予定のどの範囲に{action}を適用しますか？',
    '이 일정만': 'この予定のみ',
    '이후 일정': 'これ以降の予定',
    '전체 반복': 'すべての予定',
    '전체 삭제': 'すべて削除',
    '일정을 옮기는 중': '予定を読み込み中',
    '{count}개 캘린더 가져오기': '{count}個のカレンダーを読み込む',
    '가져올 수 있는 {provider}가 없습니다.': '読み込める{provider}カレンダーがありません。',
    '가져오기 완료: {imported}개 추가, {skipped}개 중복 제외, {failed}개 실패':
        '読み込み完了：{imported}件追加、{skipped}件の重複を除外、{failed}件失敗',
    '캘린더 권한 또는 연결 상태를 확인해 주세요.': 'カレンダーの権限または接続状態を確認してください。',
    '가져올 캘린더를 선택해 주세요.': '読み込むカレンダーを選択してください。',
    '설정에서 Daily의 캘린더 전체 접근을 허용해 주세요.': '設定でDailyにカレンダーへのフルアクセスを許可してください。',
    '캘린더 접근이 허용되지 않았습니다.': 'カレンダーへのアクセスが許可されませんでした。',
    'Google 계정 로그인이 필요합니다.': 'Googleアカウントへのログインが必要です。',
    'Google Calendar 응답 형식이 올바르지 않습니다.': 'Google Calendarから無効な応答が返されました。',
    '{title} 불러오기': '{title}を読み込む',
    '잠금 상태에서는 화면을 볼 수 없습니다.': 'ロック中は画面を表示できません。',
    '잠금 상태입니다.': 'ロック中',
    'PIN 입력': 'PINを入力',
    '비밀번호를 통해 잠금해제': 'PINでロック解除',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 확인합니다.':
        'Face ID、Touch ID、または端末のパスワードで確認します。',
    '시스템 잠금으로 해제': 'システム認証で解除',
    'PIN이 일치하지 않습니다.': 'PINが一致しません。',
    'Daily 잠금을 해제하려면 인증이 필요합니다.': 'Dailyのロック解除には認証が必要です。',
    '시스템 인증을 완료하지 못했습니다.': 'システム認証を完了できませんでした。',
    '생체인식을 완료하지 못했습니다. PIN을 입력해 주세요.': '生体認証を完了できませんでした。PINを入力してください。',
    '일정이 없습니다.': '予定がありません。',
    '시작 시각 · 중지 또는 10분 후 다시 알림': '開始時刻・停止または10分後に再通知',
    '{time} · 중지 또는 10분 후 다시 알림': '{time}・停止または10分後に再通知',
    'Apple 로그인 창을 여는 중입니다.': 'Appleサインインを開いています。',
    'Apple 로그인이 취소되었습니다.': 'Appleサインインがキャンセルされました。',
    'Apple 로그인이 완료되었습니다.': 'Appleサインインが完了しました。',
    'Apple 로그인이 완료되었습니다. 연결된 Google Drive 동기화를 복원했습니다.':
        'Appleサインインが完了し、連携済みのGoogle Drive同期を復元しました。',
    'Apple 연동을 해지했습니다.': 'Apple連携を解除しました。',
    'Google 로그인 창을 여는 중입니다.': 'Googleログインを開いています。',
    'Google Drive 연결이 취소되었습니다. 다시 연결할 수 있습니다.':
        'Google Drive接続がキャンセルされました。再接続できます。',
    '알림 권한 요청을 여는 중입니다.': '通知権限リクエストを開いています。',
    '알림 권한 설정을 확인했습니다.': '通知権限設定を確認しました。',
    '앱을 벗어난 동안 화면만 가리고 복귀하면 자동으로 해제합니다.': 'アプリを離れている間だけ画面を隠し、戻ると自動解除します。',
    'Daily 전용 PIN으로 잠그며 생체인식을 선택해서 함께 사용할 수 있습니다.':
        'Daily専用PINでロックし、生体認証も任意で利用できます。',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 인증합니다.':
        'Face ID、Touch ID、または端末のパスワードで認証します。',
    '일정 알림, 아침 브리핑, D-day 알림': '予定通知、朝のブリーフィング、D-day通知',
    'Apple, Google, 동기화 및 계정 관리': 'Apple、Google、同期、アカウント管理',
    '월 달력의 각 날짜에 음력 날짜를 함께 표시합니다.': '月間カレンダーの各日に旧暦の日付も表示します。',
    '상하 스크롤에서는 월 경계를 명확히 구분하기 위해 사용할 수 없습니다.': '月の境界を明確にするため、上下スクロールでは利用できません。',
    '월간 달력의 첫주와 마지막 주에 이전·다음 달을 표시합니다.': '月間カレンダーの最初と最後の週に前後の月を表示します。',
    '앱을 열었을 때 먼저 보여줄 달력 보기': 'アプリ起動時に最初に表示するカレンダー',
    '앱을 다시 열 때 사용자를 확인합니다.': 'アプリを再度開くときにユーザーを確認します。',
    'AI': 'AI',
    'Gemini 사용': 'Geminiを使用',
    '민감 문장 AI 차단': '機密性の高い文章をAIから除外',
    'Apple 캘린더 또는 Google 캘린더에서 가져옵니다.': 'AppleカレンダーまたはGoogleカレンダーから読み込みます。',
    'Samsung 캘린더 또는 Google 캘린더에서 가져옵니다.': 'SamsungカレンダーまたはGoogleカレンダーから読み込みます。',
    '월간, 주간, 일간 보기로 필요한 일정에 빠르게 집중하세요.': '月・週・日表示で必要な予定にすぐ集中できます。',
    '자연스럽게 일정을 기록하고 일정 알림과 아침 브리핑을 받아보세요.': '自然に予定を記録し、予定通知と朝のブリーフィングを受け取れます。',
    'D-day와 분류를 활용하고 Google Drive로 여러 기기에서 이어서 사용하세요.':
        'D-dayとカテゴリを活用し、Google Driveで複数端末から続けて利用できます。',
    'Apple 또는 Google 계정을 연결하거나 계정 없이 로컬로 시작할 수 있습니다.':
        'AppleまたはGoogleを連携するか、アカウントなしでローカル利用を開始できます。',
    '달력과 일정 목록에 D-day를 함께 표시합니다.': 'カレンダーと予定一覧にD-dayを表示します。',
    '매일 지정한 시간에 오늘 일정을 알려줍니다.': '毎日指定した時刻に今日の予定をお知らせします。',
    'GitHub 제보 양식을 기본 브라우저에서 엽니다.': '既定のブラウザでGitHubの報告フォームを開きます。',
    'GitHub Repository를 열 수 없습니다.': 'GitHubリポジトリを開けません。',
    '버그 제보 페이지를 열 수 없습니다. 잠시 후 다시 시도하세요.': '不具合報告ページを開けません。しばらくしてから再試行してください。',
    '현재 PIN 없는 잠금 방식에서 변경을 계속할까요?': '現在のPINなしロックから変更を続けますか？',
    '0 이상의 숫자를 입력하세요.': '0以上の数値を入力してください。',
    '{count} 이상의 숫자를 입력하세요.': '{count}以上の数値を入力してください。',
    'PIN을 계속 입력하거나 지워서 다시 입력하세요.': 'PINの入力を続けるか、消去して再入力してください。',
    'Touch ID 또는 Apple Watch로 Daily PIN 잠금을 해제합니다.':
        'Touch IDまたはApple WatchでDailyのPINロックを解除します。',
    'Daily PIN 잠금을 생체인식으로 해제합니다.': '生体認証でDailyのPINロックを解除します。',
    '시스템 알림 설정을 열 수 없습니다. OS 설정에서 Daily 알림을 허용하세요.':
        '通知設定を開けません。OS設定でDailyの通知を許可してください。',
    'Gemini API 키': 'Gemini APIキー',
    'Android에서는 시스템 설정 > 앱 > Daily > 알림에서 허용을 켜세요.':
        'Androidでは「設定 > アプリ > Daily > 通知」で通知を許可してください。',
    '종일 일정은 설정의 종일 알림 시간을 기준으로 예약됩니다.': '終日予定は設定の終日通知時刻を基準に予約されます。',
    '켜면 macOS 알림 권한을 요청하고 시작 시각에 시스템 알림을 전달합니다.':
        'macOSの通知権限を要求し、開始時刻にシステム通知を送信します。',
    '켜면 시스템 알람 권한을 요청하고 정시 알림을 알람으로 대체합니다.': 'アラーム権限を要求し、開始時刻の通知をアラームに置き換えます。',
    '선택한 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        '選択した時刻に音と再通知付きのmacOSシステム通知を送信します。',
    '시작 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        '開始時刻に音と再通知付きのmacOSシステム通知を送信します。',
    '선택한 시각에 시스템 알람이 울립니다.': '選択した時刻にシステムアラームが鳴ります。',
    '시작 시각의 정시 알림을 시스템 알람으로 대체합니다.': '開始時刻の通知をシステムアラームに置き換えます。',
    'Google Drive 연결이 완료되었습니다.': 'Google Driveに接続しました。',
    'Google Drive 복원 완료': 'Google Driveからの復元が完了しました',
    '요청을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.': 'リクエストを完了できませんでした。しばらくしてから再試行してください。',
    '네트워크 연결을 확인한 뒤 다시 시도해 주세요.': 'ネットワーク接続を確認して再試行してください。',
    'Google Drive 연결이 만료되었습니다. 다시 연결해 주세요.':
        'Google Drive接続の有効期限が切れました。再接続してください。',
    'Google Drive 권한이 부족합니다. 다시 연결해 권한을 승인해 주세요.':
        'Google Driveの権限が不足しています。再接続して権限を許可してください。',
    'Google Drive 요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.':
        'Google Driveへのリクエストが多すぎます。しばらくしてから再試行してください。',
    'Google Drive 서버 응답이 불안정합니다. 잠시 후 다시 시도해 주세요.':
        'Google Driveの応答が不安定です。しばらくしてから再試行してください。',
    'PIN 없음': 'PINなし',
    '시스템': 'システム',
    '즉시 알림을 보내고 예약 상태를 확인합니다.': '通知をすぐに送信し、予約状態を確認します。',
    'PIN은 4자리 이상이어야 합니다.': 'PINは4桁以上にしてください。',
    'PIN이 일치하지 않습니다. 다시 입력하세요.': 'PINが一致しません。再入力してください。',
    '마지막 성공: {time}': '最終成功：{time}',
    '새 일정에 알림을 자동으로 추가하지 않습니다.': '新しい予定に通知を自動追加しません。',
    'Apple 캘린더': 'Appleカレンダー',
    'Samsung 캘린더': 'Samsungカレンダー',
    'Google 캘린더': 'Googleカレンダー',
    '공휴일': '祝日',
    '신정': '元日',
    '삼일절': '三一節',
    '노동절': '労働節',
    '어린이날': 'こどもの日',
    '현충일': '顕忠日',
    '제헌절': '制憲節',
    '광복절': '光復節',
    '개천절': '開天節',
    '한글날': 'ハングルの日',
    '기독탄신일': 'クリスマス',
    '설날 연휴': '旧正月連休',
    '설날': '旧正月',
    '부처님 오신 날': '釈迦誕生日',
    '추석 연휴': '秋夕連休',
    '추석': '秋夕',
    '대체공휴일': '振替休日',
    '반복 없음': '繰り返さない',
    '매일': '毎日',
    '매주': '毎週',
    '매월': '毎月',
    '매년': '毎年',
    '반복 종료일': '繰り返し終了日',
    '{count}회': '{count}回',
    '{count}일마다': '{count}日ごと',
    '{count}주마다': '{count}週ごと',
    '{count}개월마다': '{count}か月ごと',
    '{count}년마다': '{count}年ごと',
    '{count}번마다': '{count}回ごと',
    'AI 설정': 'AI設定',
    'Daily 개선 참여': 'Dailyの改善に協力',
    'Daily 계정의 Apple/Google 연결 및 병합 정보, Google Drive AppData 백업, 이 기기의 모든 일정과 설정을 삭제하고 시작 화면으로 돌아갑니다. 향후 iCloud 저장 데이터도 이 경로에서 함께 삭제됩니다. 이 작업은 되돌릴 수 없습니다.':
        'DailyアカウントのApple／Google連携・統合情報、Google Drive AppDataのバックアップ、このデバイスのすべての予定と設定を削除し、開始画面に戻ります。今後iCloud保存データもこの経路で削除されます。この操作は取り消せません。',
    'Daily를 어떻게\n시작할까요?': 'Dailyをどのように\n始めますか？',
    'Daily의 AI 기능 준비 상태를 확인합니다.': 'DailyのAI機能の準備状況を確認します。',
    'Google Drive AppData의 일정과 설정을 이 기기에 복원할까요? 이 기기의 더 최신이거나 아직 백업되지 않은 변경은 유지됩니다.':
        'Google Drive AppDataの予定と設定をこのデバイスに復元しますか？このデバイス上の新しい変更や未バックアップの変更は保持されます。',
    'Google 계정 연결을 해제할까요? Google Drive AppData 백업은 유지하거나 함께 삭제할 수 있습니다. 로컬 일정과 설정은 유지됩니다.':
        'Googleアカウントの連携を解除しますか？Google Drive AppDataのバックアップは保持または削除できます。ローカルの予定と設定は保持されます。',
    'Google 연결은 앱 전용 Drive AppData 백업과 동기화에만 사용하며 일반 Drive 파일은 읽거나 수정하지 않습니다.':
        'Google連携はアプリ専用Drive AppDataのバックアップと同期にのみ使用し、通常のDriveファイルは読み取りも変更もしません。',
    'Siri 단축어 추가하기': 'Siriショートカットを追加',
    'Siri 또는 단축어로 Daily 작업을 실행하면 날짜별 기록이 여기에 표시됩니다.':
        'Siriまたはショートカットで実行したDailyの操作が日付ごとにここへ表示されます。',
    'Siri와 Daily': 'SiriとDaily',
    '{month} · 일정 {count}개': '{month}・予定{count}件',
    '가져올 캘린더를 선택하면 일정과 기존 분류 색상을 Daily에 복사합니다.':
        '読み込むカレンダーを選ぶと、予定と既存の分類色をDailyにコピーします。',
    '개인정보 및 잠금': 'プライバシーとロック',
    '개인정보 및 지원': 'プライバシーとサポート',
    '계정을 연결하면 기기 간 동기화를 사용할 수 있고, 계정 없이 이 기기에서만 시작할 수도 있어요.':
        'アカウントを連携するとデバイス間で同期できます。アカウントなしでこのデバイスだけで始めることもできます。',
    '권한 설정을 완료하지 못했습니다. 나중에 설정에서 다시 시도할 수 있습니다. ({error})':
        '権限設定を完了できませんでした。後で設定から再試行できます。({error})',
    '권한은 나중에 설정에서 다시 요청하거나 변경할 수 있습니다.': '権限は後で設定から再度要求または変更できます。',
    '기록부터 완료까지': '記録から完了まで',
    '나중에': '後で',
    '더 완벽한 Daily를\n함께 만들어요.': 'より良いDailyを\n一緒に作りましょう。',
    '동의해주시면 실제 사용 흐름과 성능 문제를 익명으로 분석해 더 빠르고 안정적인 Daily를 만들 수 있어요.':
        '同意いただくと、実際の利用フローと性能上の問題を匿名で分析し、Dailyをより速く安定させることができます。',
    '마지막 단계': '最後のステップ',
    '말 한마디로\n일정을 관리하세요.': '声だけで\n予定を管理しましょう。',
    '백업할 변경 사항이 없습니다.': 'バックアップする変更はありません。',
    '버전 정보, GitHub와 버그 제보를 확인합니다.': 'バージョン情報、GitHub、バグ報告を確認します。',
    '분류 설정': '分類設定',
    '사용 흐름': '利用フロー',
    '색상, 표시 여부와 일정 정렬 순서를 관리합니다.': '色、表示状態、予定の並び順を管理します。',
    '선택을 저장하지 못했습니다. 다시 시도해 주세요.': '選択を保存できませんでした。もう一度お試しください。',
    '성능 개선': '性能改善',
    '시그널 단축어를 추가하면 Siri에게 일정을 묻거나 추가하고 수정할 수 있어요.':
        'Signalショートカットを追加すると、Siriで予定の確認・追加・編集ができます。',
    '시작 전 알림과 브리핑': '開始前の通知とブリーフィング',
    '실행': '実行',
    '아직 Google Drive에 백업되지 않은 변경이 있을 수 있습니다. 그래도 이 기기의 데이터를 삭제하고 로그아웃할까요?':
        'Google Driveにまだバックアップされていない変更がある可能性があります。それでもこのデバイスのデータを削除してログアウトしますか？',
    '알림 및 알람 허용': '通知とアラームを許可',
    '알림과 알람을\n준비할까요?': '通知とアラームを\n設定しますか？',
    '앱 정보 및 지원': 'アプリ情報とサポート',
    '언어, 테마, 글자 크기와 달력 표시 방식을 설정합니다.': '言語、テーマ、文字サイズ、カレンダーの表示方法を設定します。',
    '연락처 보호': '連絡先の保護',
    '예: “Siri야, Daily에서 시그널 실행.”이라고 말한 뒤 “내일 오전 9시에 헬스장 일정 추가해줘.”라고 이어서 말하세요.':
        '例：「Siri、DailyでSignalを実行」と言った後、「明日の午前9時にジムの予定を追加して」と続けます。',
    '오늘을 더\n가볍게 정리하세요.': '今日をもっと\n軽やかに整えましょう。',
    '오류 범주와 응답 시간': 'エラー分類と応答時間',
    '월간, 주간, 일간 보기': '月・週・日表示',
    '이 기기의 모든 일정과 설정을 삭제하고 시작 화면으로 돌아갑니다.': 'このデバイスのすべての予定と設定を削除し、開始画面に戻ります。',
    '이 기기의 일정, 설정, 로그인 정보를 삭제하고 시작 화면으로 돌아갑니다. Google Drive AppData의 백업은 삭제하지 않습니다.':
        'このデバイスの予定、設定、ログイン情報を削除して開始画面に戻ります。Google Drive AppDataのバックアップは削除しません。',
    '익명 분석 데이터와 앱 잠금을 관리합니다.': '匿名分析データとアプリロックを管理します。',
    '익명 분석 허용': '匿名分析を許可',
    '일정 내용, 검색어, 계정 정보, 위치, 광고 식별자는 수집하지 않습니다. 언제든 설정에서 변경할 수 있어요.':
        '予定内容、検索語、アカウント情報、位置情報、広告識別子は収集しません。設定からいつでも変更できます。',
    '일정 알림': '予定の通知',
    '일정 알림과 아침 브리핑을 받으려면 알림 권한이 필요합니다. 지원되는 기기에서는 일정별 알람도 사용할 수 있어요.':
        '予定通知と朝のブリーフィングには通知権限が必要です。対応デバイスでは予定ごとのアラームも利用できます。',
    '일정과 할 일': '予定とTodo',
    '일정과 할 일을 한곳에서 보고, 필요한 순간에만 알림을 받으세요.': '予定とTodoを一か所で確認し、必要なときだけ通知を受け取れます。',
    '일정을 불러오지 못했습니다. ({error})': '予定を読み込めませんでした。({error})',
    '지원 기기에서 선택 사용': '対応デバイスで任意に使用',
    '표시 옵션': '表示オプション',
    '필요한 순간 놓치지 않기': '必要な瞬間を逃さない',
    '한눈에 보는 일정': '予定をひと目で確認',
    '화면 및 달력': '表示とカレンダー',
    '화면 및 일정': '表示と予定',
    '화면과 기능 사용': '画面と機能の利用',
  },
  'zh_Hant': {
    '업데이트 중입니다': '正在更新 Daily',
    '업데이트 확인 중': '正在檢查更新',
    '최신 백업을 복원하고 있습니다.': '正在還原最新備份。',
    '안전 스냅샷을 만들고 있습니다.': '正在建立安全快照。',
    '일정을 Todo 형식으로 업데이트하고 있습니다.': '正在將行程更新為待辦格式。',
    '업데이트 결과를 확인하고 있습니다.': '正在驗證更新結果。',
    '업데이트된 일정을 백업하고 있습니다.': '正在備份已更新的行程。',
    '업데이트가 완료되었습니다.': '更新完成。',
    '업데이트를 완료하지 못했습니다': '無法完成更新',
    '다시 시도': '重試',
    '시스템 설정에 따름': '依照系統設定',
    '언어': '語言',
    '설정': '設定',
    '알림 설정': '通知設定',
    '계정 설정': '帳號設定',
    '알림': '通知',
    '계정': '帳號',
    'Siri 단축어 설정': 'Siri 捷徑設定',
    '자동 등록된 시그널 단축어와 사용 방법을 확인합니다.': '查看自動註冊的 Signal 捷徑及其使用方式。',
    '시그널 단축어 사용': '使用 Signal 捷徑',
    '시그널은 앱 설치와 함께 자동으로 등록되므로 직접 만들 필요가 없습니다.': 'Signal 會隨 App 自動註冊，因此不需要自行建立。',
    '1. Siri에게 “Daily에서 시그널 실행”이라고 말합니다.': '1. 對 Siri 說「在 Daily 執行 Signal」。',
    '2. Siri가 질문하면 원하는 일정 명령을 이어서 말합니다.': '2. Siri 詢問時，接著說出想執行的行程指令。',
    '예: “내일 오전 9시에 헬스장 일정을 추가해줘.”': '例如：「新增明天上午 9 點的健身房行程。」',
    '단축어 앱에서 Daily의 Signal App Shortcut이 등록되었는지 확인할 수 있습니다.':
        '你可以在「捷徑」App 中確認 Daily 的 Signal App Shortcut。',
    '단축어 앱에서 확인': '在捷徑 App 中確認',
    '일정을 놓을 날짜': '拖放至日期',
    '시그널 단축어를 추가하고 Siri에서 Daily 명령을 사용합니다.':
        '加入 Signal 捷徑，以便透過 Siri 使用 Daily 指令。',
    '시그널 단축어 추가 화면을 열 수 없습니다.': '無法開啟「加入 Signal 捷徑」畫面。',
    '시그널 단축어 추가': '加入 Signal 捷徑',
    '단축어 앱에서 다음 순서로 구성하세요.': '請依下列順序在「捷徑」App 中設定。',
    '1. 새 단축어를 만들고 이름을 시그널로 지정합니다.': '1. 建立新捷徑並命名為「Signal」。',
    '2. 텍스트 받아쓰기 동작을 추가합니다.': '2. 加入「聽寫文字」動作。',
    '3. Daily Signal 동작을 추가하고 받아쓰기한 텍스트를 Signal phrase에 연결합니다.':
        '3. 加入「Daily Signal」動作，並將聽寫的文字連接到 Signal phrase。',
    '단축어 생성 화면 열기': '開啟捷徑編輯器',
    '단축어 앱을 열 수 없습니다.': '無法開啟「捷徑」App。',
    'Siri 작업 기록': 'Siri 操作記錄',
    'Siri 작업 상세': 'Siri 操作詳細',
    '작업': '操作',
    '상태': '狀態',
    '실행 시각': '執行時間',
    '요약': '摘要',
    '결과': '結果',
    '시작': '開始',
    '종료': '結束',
    '종일 일정': '全天行程',
    '예': '是',
    '아니요': '否',
    '기록 전체 삭제': '清除所有記錄',
    'Siri 작업 기록 삭제': '刪除 Siri 操作記錄',
    '저장된 Siri 작업 기록을 모두 삭제하시겠습니까?': '要刪除所有已儲存的 Siri 操作記錄嗎？',
    '성공': '成功',
    '실패': '失敗',
    'Siri와 자동화로 실행한 Daily 작업을 날짜별로 확인합니다.': '依日期查看由 Siri 與自動化執行的 Daily 操作。',
    '날짜 선택': '選擇日期',
    '전체 날짜 보기': '顯示所有日期',
    '기록된 Siri 작업이 없습니다.': '尚無 Siri 操作記錄。',
    '오늘 일정 조회': '今日行程',
    '내일 일정 조회': '明日行程',
    '날짜별 일정 조회': '依日期查看行程',
    '다음 일정 조회': '下一個行程',
    'D-day 조회': 'D-day 行程',
    '달력 열기': '開啟行事曆',
    'Siri 작업': 'Siri 操作',
    '지금 듣는 중...': '正在聆聽...',
    '시그널 처리 중...': '正在處理 Signal...',
    '다시 말씀해 주세요': '請再說一次',
    '필요한 정보를 이어서 말씀해 주세요.': '請繼續提供缺少的資訊。',
    '음성 명령을 처리하지 못했습니다.': '無法處理語音指令。',
    '듣기 중지': '停止聆聽',
    '다시 듣기': '再次聆聽',
    '음성 듣기가 중단되었습니다.': '語音聆聽已中斷。',
    '이 명령을 실행할까요?': '要執行這個指令嗎？',
    '인증 또는 작업이 취소되었습니다.': '驗證或操作已取消。',
    '기기 인증을 완료하지 못했습니다.': '無法完成裝置驗證。',
    '작업을 취소했습니다.': '操作已取消。',
    '일정은 저장했지만 알림 또는 동기화 처리가 보류되었습니다.': '行程已儲存，但通知或同步處理仍在等待中。',
    '일정은 저장했으며 클라우드 동기화는 연결 후 재시도됩니다.': '行程已儲存。連結帳號後將重新嘗試雲端同步。',
    '실행 확인': '確認執行',
    '듣기 완료': '完成聆聽',
    '텍스트로 입력': '改用文字輸入',
    'Daily에 요청할 내용을 입력하세요.': '輸入要交給 Daily 的要求。',
    '화면': '顯示',
    '테마': '主題',
    '자동': '自動',
    '화이트': '淺色',
    '다크': '深色',
    '달력': '行事曆',
    '주 시작 요일': '每週起始日',
    '일': '日',
    '월': '一',
    '주 보기': '週',
    '월 보기': '月',
    '일 보기': '日',
    '음력 표시': '顯示農曆',
    '인접한 달 날짜 표시': '顯示相鄰月份日期',
    '월간 이동 방식': '月份導覽方式',
    '좌우 슬라이드': '左右滑動',
    '상하 스크롤': '上下捲動',
    '첫 화면': '啟動畫面',
    '앱을 열었을 때 먼저 보여줄 화면': '開啟 App 時最先顯示的畫面',
    '기본 보기': '預設檢視',
    '주간·일간 표시 방식': '週／日顯示方式',
    '목록': '清單',
    '스케줄': '時間表',
    '종일 일정 표시': '顯示全日行程',
    '종일 일정 숨기기': '隱藏全日行程',
    '주간': '週',
    '월간': '月',
    '일간': '日',
    '전체 UI 글자 크기': '介面文字大小',
    '기본': '預設',
    '가운데': '置中',
    '일정 제목 정렬': '行程標題對齊',
    '일정 정렬 우선순위': '行程排序優先順序',
    '분류 우선': '分類優先',
    '시간 우선': '時間優先',
    '길게 눌러 순서 변경': '長按以重新排序',
    '크게': '大',
    '더 크게': '特大',
    '개인정보': '隱私權',
    '익명 사용성 분석 허용': '允許匿名使用情況分析',
    '일정 내용, 검색어, 계정 정보 없이 화면과 기능 사용, 오류 범주, 성능 정보만 수집합니다.':
        '僅收集畫面與功能使用、錯誤分類及效能資訊，不包含行程內容、搜尋詞或帳號資訊。',
    '분석 데이터 삭제': '刪除分析資料',
    '이 기기에 전송 대기 중인 익명 분석 데이터를 삭제합니다.': '刪除此裝置上等待傳送的匿名分析資料。',
    '이 기기에 전송 대기 중인 익명 분석 데이터를 삭제할까요? 이미 전송되어 집계된 데이터는 계정이나 기기와 연결되지 않아 특정 사용자를 식별하거나 되돌릴 수 없습니다.':
        '要刪除此裝置上等待傳送的匿名分析資料嗎？已傳送的資料不會連結帳號或裝置，且只會彙總，因此無法識別或還原特定使用者的資料。',
    '전송 대기 분석 데이터를 삭제했습니다.': '已刪除等待傳送的分析資料。',
    '앱 잠금': 'App 鎖定',
    'PIN 없이 잠금': '無 PIN 鎖定',
    'PIN 잠금': 'PIN 鎖定',
    '시스템 잠금 비밀번호': '系統驗證',
    '생체인식 잠금 해제': '生物辨識解鎖',
    '분류': '分類',
    '분류 추가': '新增分類',
    'AI 기능': 'AI 功能',
    '개발 중입니다.': '開發中。',
    '캘린더 데이터 옮기기': '匯入行事曆資料',
    '건너뛰기': '略過',
    '이전': '上一步',
    '다음': '下一步',
    '일정을 한눈에': '行程一目瞭然',
    '기록하고 바로 알림 받기': '記錄並立即接收提醒',
    '중요한 날까지 이어서': '掌握每個重要日子',
    'Daily 시작하기': '開始使用 Daily',
    'Apple로 계속': '使用 Apple 繼續',
    '로컬로 시작': '在本機開始',
    'Google 연결 중': '正在連接 Google',
    'Google로 계속': '使用 Google 繼續',
    '연결 취소': '取消連接',
    '알림 권한 허용': '允許通知',
    '검색': '搜尋',
    '필터': '篩選',
    '오늘': '今天',
    '빠른 보기': '快速檢視',
    '일정 추가': '新增行程',
    '일정 수정': '編輯行程',
    '저장': '儲存',
    '취소': '取消',
    '삭제': '刪除',
    '수정': '編輯',
    '제목': '標題',
    '시간': '時間',
    '장소': '地點',
    '메모': '備註',
    '종일': '全天',
    '반복': '重複',
    '없음': '無',
    '완료': '完成',
    '지도 바로가기': '在地圖中開啟',
    '월간 미니 캘린더': '月份迷你行事曆',
    '오늘 일정': '今日行程',
    '일정 없음': '沒有行程',
    '중요한 날짜': '重要日期',
    'D-day 일정 없음': '沒有 D-day 行程',
    '일정 {count}개': '{count} 個行程',
    'D-day {count}개': '{count} 個 D-day 行程',
    '공휴일 {count}개': '{count} 個國定假日',
    '검색 닫기': '關閉搜尋',
    '현재 보기에서 검색': '搜尋目前檢視',
    'D-day 일정만 보기': '僅顯示 D-day 行程',
    '공휴일 표시': '顯示國定假日',
    '공휴일 날짜 배경': '國定假日日期背景',
    '공휴일 분류 색상을 날짜 배경에 표시합니다.': '使用國定假日分類顏色作為日期背景。',
    '분류 표시': '顯示分類',
    '검색어 지우기': '清除搜尋',
    'AI 입력 닫기': '關閉 AI 輸入',
    '일정을 입력하세요': '輸入行程',
    '등록': '新增',
    '이 일정으로 등록할까요?': '要新增此行程嗎？',
    '열기': '開啟',
    '추가 상세정보가 없습니다.': '沒有其他詳細資訊。',
    '주': '週',
    '개월': '個月',
    '년': '年',
    '번': '次',
    '제목을 입력하세요.': '請輸入標題。',
    '시작일': '開始日期',
    '종료일': '結束日期',
    '시작 시간': '開始時間',
    '종료 시간': '結束時間',
    '알림 직접 입력': '自訂提醒',
    '일정 알람': '行程鬧鐘',
    '종일 일정 알람 시각': '全天行程鬧鐘時間',
    'URL / 링크': 'URL / 連結',
    '날씨': '天氣',
    '예: 흐림': '例如：陰天',
    'D-day 표시': '顯示 D-day',
    '제목, 메모, 장소 검색': '搜尋標題、備註或地點',
    '검색 결과가 없습니다.': '沒有搜尋結果。',
    'Apple 연동 해지': '中斷 Apple 連結',
    'Google 연동 해지': '中斷 Google 連結',
    'D-day 알림': 'D-day 提醒',
    'Daily 계정': 'Daily 帳號',
    'Daily 버전': 'Daily 版本',
    'Google Drive 동기화': 'Google Drive 同步',
    'Google Drive에서 복원': '從 Google Drive 還原',
    'Google 계정': 'Google 帳號',
    'Google 로그인 시 Daily 계정에 연결됩니다.': '使用 Google 登入時會連結至 Daily 帳號。',
    '이 계정의 Google Drive AppData에 일정을 백업하고 복원합니다.':
        '在此帳號的 Google Drive AppData 中備份及還原行程。',
    'Google 인증 세션이 없습니다. 다시 연결하면 자동 동기화가 재개됩니다.':
        '沒有 Google 驗證工作階段。重新連結後會恢復自動同步。',
    'Google 로그인 시 Drive AppData 권한도 함께 승인합니다.':
        '使用 Google 登入時也會要求 Drive AppData 存取權限。',
    '백업': '備份',
    'Google 다시 연결': '重新連結 Google',
    'Daily 계정 탈퇴': '刪除 Daily 帳號',
    '로컬 데이터 초기화': '重設本機資料',
    'Apple로 로그인됨': '已使用 Apple 登入',
    'Apple 로그인': 'Apple 登入',
    'Daily 계정에 연결된 Apple 로그인입니다.': '此 Apple 登入已連結至 Daily 帳號。',
    'Apple 로그인만으로 Daily를 사용할 수 있습니다.': '只使用 Apple 登入也能使用 Daily。',
    'Apple 또는 Google 계정을 연결할 수 있습니다.': '可以連結 Apple 或 Google 帳號。',
    '{providers} 로그인 연결됨': '已連結 {providers} 登入',
    '아직 동기화 기록이 없습니다.': '尚無同步記錄。',
    '백업 중': '正在備份',
    '복원 중': '正在還原',
    '동기화 중': '正在同步',
    '다른 기기 변경 확인 중': '正在檢查其他裝置的變更',
    '백업 완료': '備份完成',
    '복원 완료': '還原完成',
    '동기화 완료': '同步完成',
    '최신 상태': '已是最新狀態',
    '일부 백업 보류 · 먼저 복원 필요': '部分備份擱置・請先還原',
    '다른 기기 변경 확인 준비 중': '正在準備檢查其他裝置的變更',
    '동기화 완료 · 다른 기기 변경 복원': '同步完成・已還原其他裝置的變更',
    'PIN 확인': '驗證 PIN',
    '계속': '繼續',
    '기본 알림 직접 입력': '輸入預設提醒',
    '동기화 상태': '同步狀態',
    '로그아웃': '登出',
    '아침 브리핑': '晨間摘要',
    '복원': '還原',
    '분류 삭제': '刪除分類',
    '분류 수정': '編輯分類',
    '사용자 지정 색상': '自訂顏色',
    '시간 선택': '選擇時間',
    '시간 표시 방식': '時間格式',
    '시스템 알림 설정 열기': '開啟系統通知設定',
    '백업 삭제 후 해제': '刪除備份並中斷連結',
    '백업 없이 로그아웃': '不備份直接登出',
    '백업을 완료하지 못했습니다': '無法完成備份',
    '버그 제보': '回報問題',
    'Google 로그인 사용자만 GitHub 이슈를 자동 등록할 수 있습니다.':
        '只有使用 Google 登入的使用者才能自動建立 GitHub Issue。',
    'Google 로그인이 필요합니다.': '需要 Google 登入',
    '확인': '確定',
    '버그 제보는 Google 로그인으로 Daily를 사용 중인 경우에만 등록할 수 있습니다. 계정 설정에서 Google 계정을 연결해 주세요.':
        '只有使用 Google 登入 Daily 時才能提交錯誤回報。請在帳號設定中連結 Google 帳號。',
    'Google 계정 이메일 {email}을 제보 연락처로 수집합니다. 이메일은 공개 GitHub 이슈에 표시되지 않고 Daily 서버에 비공개로 저장됩니다.':
        '系統會收集 Google 帳號電子郵件 {email} 作為回報聯絡方式。電子郵件不會顯示於公開 GitHub Issue，並會私密儲存在 Daily 伺服器。',
    '작성한 제보 내용은 공개 GitHub 이슈로 등록됩니다. 개인정보를 입력하지 마세요.':
        '您填寫的回報內容將建立為公開 GitHub Issue。請勿輸入個人資料。',
    '문제 설명': '問題說明',
    '재현 방법': '重現步驟',
    '예상 동작': '預期行為',
    '실제 동작': '實際行為',
    '필수 입력 항목입니다.': '此欄位為必填。',
    'GitHub 이슈 등록': '建立 GitHub Issue',
    '버그 제보를 등록했습니다.': '已建立錯誤回報',
    'GitHub 이슈 #{number}로 등록되었습니다.': '已建立為 GitHub Issue #{number}。',
    'GitHub에서 보기': '在 GitHub 查看',
    'Google 로그인 정보를 확인할 수 없습니다.': '無法驗證 Google 登入資訊。',
    '버그 제보 서버에 연결할 수 없습니다.': '無法連線至錯誤回報伺服器。',
    'Google 로그인 상태를 확인한 뒤 다시 시도해 주세요.': '請確認 Google 登入狀態後再試一次。',
    '버그 제보 요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.': '錯誤回報請求過多，請稍後再試。',
    '버그 제보 내용을 다시 확인해 주세요.': '請重新檢查錯誤回報內容。',
    'GitHub 이슈를 생성하지 못했습니다. 잠시 후 다시 시도해 주세요.': '無法建立 GitHub Issue，請稍後再試。',
    '버그 제보 결과를 확인할 수 없습니다.': '無法驗證錯誤回報結果。',
    '버그 제보를 등록하지 못했습니다. 잠시 후 다시 시도해 주세요.': '無法提交錯誤回報，請稍後再試。',
    '보내기': '傳送',
    '연동 해지': '中斷連結',
    '연동만 해제': '僅中斷連結',
    '저장 내용 초기화': '刪除儲存資料',
    '적용': '套用',
    '직접 입력': '自訂',
    '잠금 방식 변경': '變更鎖定方式',
    '잠금 방식 선택': '選擇鎖定方式',
    '한 자리 지우기': '刪除一位數',
    '앱 정보': 'App 資訊',
    '일정이 시작됩니다.': '行程即將開始。',
    '일정 시작 {time}입니다.': '行程將於{time}開始。',
    'D-day 일정 알림입니다.': '這是 D-day 行程提醒。',
    '오늘의 일정': '今日行程',
    '오늘 등록된 일정이 없습니다.': '今天沒有行程。',
    ' 외 {count}개 더 있습니다.': '，另有 {count} 個',
    '정시': '準時',
    '{count}분 전': '{count} 分鐘前',
    '{count}일 전': '{count} 天前',
    '{count}시간 전': '{count} 小時前',
    '앱 잠금을 해제하려면 PIN을 입력하세요.': '輸入 PIN 以解除 App 鎖定。',
    '이 기기에서 시스템 잠금 인증을 사용할 수 없습니다.': '此裝置無法使用系統驗證。',
    '기본 일정 알림': '預設行程提醒',
    '몇 분 전에 알릴까요?': '要提前幾分鐘提醒？',
    '종일 일정 알림 시간': '全天行程提醒時間',
    '종일 일정의 알림 기준 시간': '全天行程的預設提醒時間',
    '아침 브리핑 시간': '晨間摘要時間',
    '브리핑을 받을 시간': '接收摘要的時間',
    'D-day 알림 직접 입력': '自訂 D-day 提醒',
    'D-day 기준 일수. 예: -7, 0': '相對 D-day 的天數，例如 -7、0',
    '앱 잠금 PIN 설정': '設定 App 鎖定 PIN',
    '잠금 방식': '鎖定方式',
    '버전 {version} · 더블 클릭하여 Github 확인하기': '版本 {version}・按兩下查看 GitHub',
    '이름': '名稱',
    '색상': '顏色',
    '"{category}" 분류를 삭제할까요?': '要刪除「{category}」分類嗎？',
    '닫기': '關閉',
    '검색/필터': '搜尋／篩選',
    '반복 종료': '重複結束',
    '종료 없음': '永不',
    '날짜까지': '到指定日期',
    '횟수만큼': '指定次數',
    '반복 간격': '重複間隔',
    '몇 {unit}마다 반복할까요?': '每幾{unit}重複一次？',
    '반복 횟수': '重複次數',
    '몇 회 반복할까요?': '要重複幾次？',
    '제목을 입력해야 일정을 저장할 수 있습니다.': '請輸入標題後再儲存行程。',
    '종료일은 시작일과 같거나 이후여야 합니다.': '結束日期必須等於或晚於開始日期。',
    '종료 시간은 시작 시간보다 늦어야 합니다.': '結束時間必須晚於開始時間。',
    '반복 간격은 1 이상이어야 합니다.': '重複間隔必須至少為 1。',
    '반복 알람은 추후 루틴 기능에서 사용할 수 있습니다.': '重複鬧鐘將於日後的例行功能中提供。',
    '알람 지원 상태를 확인하고 있습니다.': '正在檢查鬧鐘支援狀態。',
    '이 운영체제에서는 일정 알람을 사용할 수 없습니다.': '此作業系統不支援行程鬧鐘。',
    '시스템 설정에서 Daily의 알람 권한을 허용해야 합니다.': '請在系統設定中允許 Daily 使用鬧鐘。',
    '반복 일정 수정': '編輯重複行程',
    '반복 일정 이동': '移動重複行程',
    '이 반복 일정의 어느 범위를 이동할까요?': '要移動此重複行程的哪個範圍？',
    '반복 일정 삭제': '刪除重複行程',
    '일정 삭제': '刪除行程',
    '"{title}" 일정을 삭제할까요?': '要刪除「{title}」嗎？',
    '이 반복 일정의 어느 범위에 {action}을 적용할까요?': '要將{action}套用到此重複行程的哪個範圍？',
    '이 일정만': '僅此行程',
    '이후 일정': '此行程及之後',
    '전체 반복': '所有行程',
    '전체 삭제': '全部刪除',
    '일정을 옮기는 중': '正在匯入行程',
    '{count}개 캘린더 가져오기': '匯入 {count} 個行事曆',
    '가져올 수 있는 {provider}가 없습니다.': '沒有可匯入的 {provider} 行事曆。',
    '가져오기 완료: {imported}개 추가, {skipped}개 중복 제외, {failed}개 실패':
        '匯入完成：新增 {imported} 個、略過 {skipped} 個重複項目、{failed} 個失敗',
    '캘린더 권한 또는 연결 상태를 확인해 주세요.': '請檢查行事曆權限或連線狀態。',
    '가져올 캘린더를 선택해 주세요.': '請選擇要匯入的行事曆。',
    '설정에서 Daily의 캘린더 전체 접근을 허용해 주세요.': '請在「設定」中允許 Daily 完整存取行事曆。',
    '캘린더 접근이 허용되지 않았습니다.': '未允許存取行事曆。',
    'Google 계정 로그인이 필요합니다.': '請先登入 Google 帳號。',
    'Google Calendar 응답 형식이 올바르지 않습니다.': 'Google Calendar 傳回了無效的回應。',
    '{title} 불러오기': '載入 {title}',
    '잠금 상태에서는 화면을 볼 수 없습니다.': 'App 鎖定時無法查看內容。',
    '잠금 상태입니다.': '已鎖定',
    'PIN 입력': '輸入 PIN',
    '비밀번호를 통해 잠금해제': '使用 PIN 解鎖',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 확인합니다.': '使用 Face ID、Touch ID 或裝置密碼驗證。',
    '시스템 잠금으로 해제': '使用系統驗證解鎖',
    'PIN이 일치하지 않습니다.': 'PIN 不相符。',
    'Daily 잠금을 해제하려면 인증이 필요합니다.': '需要驗證才能解除 Daily 鎖定。',
    '시스템 인증을 완료하지 못했습니다.': '未能完成系統驗證。',
    '생체인식을 완료하지 못했습니다. PIN을 입력해 주세요.': '未能完成生物辨識驗證，請輸入 PIN。',
    '일정이 없습니다.': '沒有行程。',
    '시작 시각 · 중지 또는 10분 후 다시 알림': '開始時間・停止或延後 10 分鐘提醒',
    '{time} · 중지 또는 10분 후 다시 알림': '{time}・停止或延後 10 分鐘提醒',
    'Apple 로그인 창을 여는 중입니다.': '正在開啟 Apple 登入。',
    'Apple 로그인이 취소되었습니다.': '已取消 Apple 登入。',
    'Apple 로그인이 완료되었습니다.': 'Apple 登入完成。',
    'Apple 로그인이 완료되었습니다. 연결된 Google Drive 동기화를 복원했습니다.':
        'Apple 登入完成，已恢復連結的 Google Drive 同步。',
    'Apple 연동을 해지했습니다.': '已中斷 Apple 連結。',
    'Google 로그인 창을 여는 중입니다.': '正在開啟 Google 登入。',
    'Google Drive 연결이 취소되었습니다. 다시 연결할 수 있습니다.': '已取消 Google Drive 連線，您可以重新連線。',
    '알림 권한 요청을 여는 중입니다.': '正在開啟通知權限要求。',
    '알림 권한 설정을 확인했습니다.': '已檢查通知權限設定。',
    '앱을 벗어난 동안 화면만 가리고 복귀하면 자동으로 해제합니다.': '離開 App 時隱藏內容，返回時自動解除。',
    'Daily 전용 PIN으로 잠그며 생체인식을 선택해서 함께 사용할 수 있습니다.':
        '使用 Daily 專用 PIN 鎖定，也可選擇搭配生物辨識。',
    '기기의 Face ID, Touch ID 또는 시스템 비밀번호로 인증합니다.': '使用 Face ID、Touch ID 或裝置密碼驗證。',
    '일정 알림, 아침 브리핑, D-day 알림': '行程提醒、晨間摘要與 D-day 提醒',
    'Apple, Google, 동기화 및 계정 관리': 'Apple、Google、同步與帳號管理',
    '월 달력의 각 날짜에 음력 날짜를 함께 표시합니다.': '在月份行事曆的每個日期旁顯示農曆日期。',
    '상하 스크롤에서는 월 경계를 명확히 구분하기 위해 사용할 수 없습니다.': '為清楚區分月份邊界，上下捲動時無法使用。',
    '월간 달력의 첫주와 마지막 주에 이전·다음 달을 표시합니다.': '在月份行事曆的第一週與最後一週顯示相鄰月份。',
    '앱을 열었을 때 먼저 보여줄 달력 보기': '開啟 App 時先顯示的行事曆檢視',
    '앱을 다시 열 때 사용자를 확인합니다.': '重新開啟 App 時驗證使用者。',
    'AI': 'AI',
    'Gemini 사용': '使用 Gemini',
    '민감 문장 AI 차단': '阻擋敏感文字傳送至 AI',
    'Apple 캘린더 또는 Google 캘린더에서 가져옵니다.': '從 Apple 行事曆或 Google 日曆匯入。',
    'Samsung 캘린더 또는 Google 캘린더에서 가져옵니다.': '從 Samsung 行事曆或 Google 日曆匯入。',
    '월간, 주간, 일간 보기로 필요한 일정에 빠르게 집중하세요.': '使用月、週、日檢視快速聚焦需要的行程。',
    '자연스럽게 일정을 기록하고 일정 알림과 아침 브리핑을 받아보세요.': '自然地記錄行程，並接收行程提醒與晨間摘要。',
    'D-day와 분류를 활용하고 Google Drive로 여러 기기에서 이어서 사용하세요.':
        '使用 D-day 與分類，並透過 Google Drive 在多部裝置上接續使用。',
    'Apple 또는 Google 계정을 연결하거나 계정 없이 로컬로 시작할 수 있습니다.':
        '可連結 Apple 或 Google 帳號，或不使用帳號直接在本機開始。',
    '달력과 일정 목록에 D-day를 함께 표시합니다.': '在行事曆與行程列表中顯示 D-day。',
    '매일 지정한 시간에 오늘 일정을 알려줍니다.': '每天在指定時間顯示今日行程。',
    'GitHub 제보 양식을 기본 브라우저에서 엽니다.': '使用預設瀏覽器開啟 GitHub 回報表單。',
    'GitHub Repository를 열 수 없습니다.': '無法開啟 GitHub 儲存庫。',
    '버그 제보 페이지를 열 수 없습니다. 잠시 후 다시 시도하세요.': '無法開啟問題回報頁面，請稍後再試。',
    '현재 PIN 없는 잠금 방식에서 변경을 계속할까요?': '要繼續從目前的無 PIN 鎖定方式變更嗎？',
    '0 이상의 숫자를 입력하세요.': '請輸入大於或等於 0 的數字。',
    '{count} 이상의 숫자를 입력하세요.': '請輸入大於或等於 {count} 的數字。',
    'PIN을 계속 입력하거나 지워서 다시 입력하세요.': '請繼續輸入 PIN，或清除後重新輸入。',
    'Touch ID 또는 Apple Watch로 Daily PIN 잠금을 해제합니다.':
        '使用 Touch ID 或 Apple Watch 解除 Daily PIN 鎖定。',
    'Daily PIN 잠금을 생체인식으로 해제합니다.': '使用生物辨識解除 Daily PIN 鎖定。',
    '시스템 알림 설정을 열 수 없습니다. OS 설정에서 Daily 알림을 허용하세요.':
        '無法開啟通知設定，請在系統設定中允許 Daily 通知。',
    'Gemini API 키': 'Gemini API 金鑰',
    'Android에서는 시스템 설정 > 앱 > Daily > 알림에서 허용을 켜세요.':
        '在 Android 上，請前往「設定 > 應用程式 > Daily > 通知」允許通知。',
    '종일 일정은 설정의 종일 알림 시간을 기준으로 예약됩니다.': '全天行程會依照設定中的全天提醒時間排程。',
    '켜면 macOS 알림 권한을 요청하고 시작 시각에 시스템 알림을 전달합니다.':
        '開啟後會要求 macOS 通知權限，並在開始時間傳送系統通知。',
    '켜면 시스템 알람 권한을 요청하고 정시 알림을 알람으로 대체합니다.': '開啟後會要求鬧鐘權限，並以鬧鐘取代開始時間通知。',
    '선택한 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        '在選定時間傳送具備聲音與稍後提醒的 macOS 系統通知。',
    '시작 시각에 소리와 다시 알림이 있는 macOS 시스템 알림을 전달합니다.':
        '在開始時間傳送具備聲音與稍後提醒的 macOS 系統通知。',
    '선택한 시각에 시스템 알람이 울립니다.': '系統鬧鐘會在選定時間響起。',
    '시작 시각의 정시 알림을 시스템 알람으로 대체합니다.': '以系統鬧鐘取代開始時間通知。',
    'Google Drive 연결이 완료되었습니다.': 'Google Drive 連線完成。',
    'Google Drive 복원 완료': 'Google Drive 還原完成',
    '요청을 완료하지 못했습니다. 잠시 후 다시 시도해 주세요.': '無法完成要求，請稍後再試。',
    '네트워크 연결을 확인한 뒤 다시 시도해 주세요.': '請檢查網路連線後再試。',
    'Google Drive 연결이 만료되었습니다. 다시 연결해 주세요.': 'Google Drive 連線已過期，請重新連線。',
    'Google Drive 권한이 부족합니다. 다시 연결해 권한을 승인해 주세요.':
        'Google Drive 權限不足，請重新連線並允許存取。',
    'Google Drive 요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.': 'Google Drive 要求過多，請稍後再試。',
    'Google Drive 서버 응답이 불안정합니다. 잠시 후 다시 시도해 주세요.': 'Google Drive 回應不穩定，請稍後再試。',
    'PIN 없음': '無 PIN',
    '시스템': '系統',
    '즉시 알림을 보내고 예약 상태를 확인합니다.': '立即傳送通知並檢查排程狀態。',
    'PIN은 4자리 이상이어야 합니다.': 'PIN 必須至少 4 位數。',
    'PIN이 일치하지 않습니다. 다시 입력하세요.': 'PIN 不相符，請重新輸入。',
    '마지막 성공: {time}': '上次成功：{time}',
    '새 일정에 알림을 자동으로 추가하지 않습니다.': '不會自動為新行程加入提醒。',
    'Apple 캘린더': 'Apple 行事曆',
    'Samsung 캘린더': 'Samsung 行事曆',
    'Google 캘린더': 'Google 日曆',
    '공휴일': '國定假日',
    '신정': '元旦',
    '삼일절': '三一節',
    '노동절': '勞動節',
    '어린이날': '兒童節',
    '현충일': '顯忠日',
    '제헌절': '制憲節',
    '광복절': '光復節',
    '개천절': '開天節',
    '한글날': '韓文日',
    '기독탄신일': '聖誕節',
    '설날 연휴': '春節連假',
    '설날': '春節',
    '부처님 오신 날': '佛誕日',
    '추석 연휴': '秋夕連假',
    '추석': '秋夕',
    '대체공휴일': '補假',
    '반복 없음': '不重複',
    '매일': '每天',
    '매주': '每週',
    '매월': '每月',
    '매년': '每年',
    '반복 종료일': '重複結束日期',
    '{count}회': '{count} 次',
    '{count}일마다': '每 {count} 天',
    '{count}주마다': '每 {count} 週',
    '{count}개월마다': '每 {count} 個月',
    '{count}년마다': '每 {count} 年',
    '{count}번마다': '每 {count} 次',
    'AI 설정': 'AI 設定',
    'Daily 개선 참여': '協助改善 Daily',
    'Daily 계정의 Apple/Google 연결 및 병합 정보, Google Drive AppData 백업, 이 기기의 모든 일정과 설정을 삭제하고 시작 화면으로 돌아갑니다. 향후 iCloud 저장 데이터도 이 경로에서 함께 삭제됩니다. 이 작업은 되돌릴 수 없습니다.':
        '刪除 Daily 帳號的 Apple／Google 連結與合併資訊、Google Drive AppData 備份，以及此裝置上的所有行程與設定，然後返回開始畫面。未來 iCloud 儲存資料也會透過此路徑一併刪除。此操作無法復原。',
    'Daily를 어떻게\n시작할까요?': '要如何\n開始使用 Daily？',
    'Daily의 AI 기능 준비 상태를 확인합니다.': '查看 Daily AI 功能的準備狀態。',
    'Google Drive AppData의 일정과 설정을 이 기기에 복원할까요? 이 기기의 더 최신이거나 아직 백업되지 않은 변경은 유지됩니다.':
        '要將 Google Drive AppData 中的行程與設定還原到此裝置嗎？此裝置上較新的變更或尚未備份的變更會保留。',
    'Google 계정 연결을 해제할까요? Google Drive AppData 백업은 유지하거나 함께 삭제할 수 있습니다. 로컬 일정과 설정은 유지됩니다.':
        '要中斷 Google 帳號連結嗎？您可以保留或一併刪除 Google Drive AppData 備份。本機行程與設定會保留。',
    'Google 연결은 앱 전용 Drive AppData 백업과 동기화에만 사용하며 일반 Drive 파일은 읽거나 수정하지 않습니다.':
        'Google 連結僅用於 App 專用 Drive AppData 的備份與同步，不會讀取或修改一般 Drive 檔案。',
    'Siri 단축어 추가하기': '加入 Siri 捷徑',
    'Siri 또는 단축어로 Daily 작업을 실행하면 날짜별 기록이 여기에 표시됩니다.':
        '透過 Siri 或捷徑執行的 Daily 操作會依日期顯示在這裡。',
    'Siri와 Daily': 'Siri 與 Daily',
    '{month} · 일정 {count}개': '{month} · {count} 個行程',
    '가져올 캘린더를 선택하면 일정과 기존 분류 색상을 Daily에 복사합니다.':
        '選取要匯入的行事曆後，會將行程與既有分類顏色複製到 Daily。',
    '개인정보 및 잠금': '隱私與鎖定',
    '개인정보 및 지원': '隱私與支援',
    '계정을 연결하면 기기 간 동기화를 사용할 수 있고, 계정 없이 이 기기에서만 시작할 수도 있어요.':
        '連結帳號即可在裝置間同步，也可以不使用帳號，僅在此裝置開始。',
    '권한 설정을 완료하지 못했습니다. 나중에 설정에서 다시 시도할 수 있습니다. ({error})':
        '無法完成權限設定。稍後可在「設定」中重試。({error})',
    '권한은 나중에 설정에서 다시 요청하거나 변경할 수 있습니다.': '稍後可在「設定」中再次要求或變更權限。',
    '기록부터 완료까지': '從記錄到完成',
    '나중에': '稍後',
    '더 완벽한 Daily를\n함께 만들어요.': '一起讓 Daily\n變得更完善。',
    '동의해주시면 실제 사용 흐름과 성능 문제를 익명으로 분석해 더 빠르고 안정적인 Daily를 만들 수 있어요.':
        '若您同意，我們會匿名分析實際使用流程與效能問題，讓 Daily 更快速、更穩定。',
    '마지막 단계': '最後一步',
    '말 한마디로\n일정을 관리하세요.': '用一句話\n管理您的行程。',
    '백업할 변경 사항이 없습니다.': '沒有需要備份的變更。',
    '버전 정보, GitHub와 버그 제보를 확인합니다.': '查看版本資訊、GitHub 與錯誤回報。',
    '분류 설정': '分類設定',
    '사용 흐름': '使用流程',
    '색상, 표시 여부와 일정 정렬 순서를 관리합니다.': '管理顏色、顯示狀態與行程排序。',
    '선택을 저장하지 못했습니다. 다시 시도해 주세요.': '無法儲存您的選擇，請再試一次。',
    '성능 개선': '效能改善',
    '시그널 단축어를 추가하면 Siri에게 일정을 묻거나 추가하고 수정할 수 있어요.':
        '加入 Signal 捷徑後，可以透過 Siri 查詢、新增或修改行程。',
    '시작 전 알림과 브리핑': '開始前提醒與摘要',
    '실행': '執行',
    '아직 Google Drive에 백업되지 않은 변경이 있을 수 있습니다. 그래도 이 기기의 데이터를 삭제하고 로그아웃할까요?':
        '可能仍有尚未備份到 Google Drive 的變更。仍要刪除此裝置上的資料並登出嗎？',
    '알림 및 알람 허용': '允許通知與鬧鐘',
    '알림과 알람을\n준비할까요?': '要設定通知\n與鬧鐘嗎？',
    '앱 정보 및 지원': 'App 資訊與支援',
    '언어, 테마, 글자 크기와 달력 표시 방식을 설정합니다.': '設定語言、主題、文字大小與行事曆顯示方式。',
    '연락처 보호': '聯絡資訊保護',
    '예: “Siri야, Daily에서 시그널 실행.”이라고 말한 뒤 “내일 오전 9시에 헬스장 일정 추가해줘.”라고 이어서 말하세요.':
        '例如，先說「Siri，在 Daily 執行 Signal」，再接著說「新增明天上午 9 點的健身房行程」。',
    '오늘을 더\n가볍게 정리하세요.': '更輕鬆地\n整理今天。',
    '오류 범주와 응답 시간': '錯誤類別與回應時間',
    '월간, 주간, 일간 보기': '月、週、日檢視',
    '이 기기의 모든 일정과 설정을 삭제하고 시작 화면으로 돌아갑니다.': '刪除此裝置上的所有行程與設定，然後返回開始畫面。',
    '이 기기의 일정, 설정, 로그인 정보를 삭제하고 시작 화면으로 돌아갑니다. Google Drive AppData의 백업은 삭제하지 않습니다.':
        '刪除此裝置上的行程、設定與登入資訊，然後返回開始畫面。Google Drive AppData 備份不會刪除。',
    '익명 분석 데이터와 앱 잠금을 관리합니다.': '管理匿名分析資料與 App 鎖定。',
    '익명 분석 허용': '允許匿名分析',
    '일정 내용, 검색어, 계정 정보, 위치, 광고 식별자는 수집하지 않습니다. 언제든 설정에서 변경할 수 있어요.':
        '不會收集行程內容、搜尋字詞、帳號資訊、位置或廣告識別碼。您可以隨時在「設定」中變更。',
    '일정 알림': '行程提醒',
    '일정 알림과 아침 브리핑을 받으려면 알림 권한이 필요합니다. 지원되는 기기에서는 일정별 알람도 사용할 수 있어요.':
        '行程提醒與晨間摘要需要通知權限。支援的裝置也可使用個別行程鬧鐘。',
    '일정과 할 일': '行程與待辦事項',
    '일정과 할 일을 한곳에서 보고, 필요한 순간에만 알림을 받으세요.': '在同一處查看行程與待辦事項，並只在需要時接收通知。',
    '일정을 불러오지 못했습니다. ({error})': '無法載入行程。({error})',
    '지원 기기에서 선택 사용': '可在支援的裝置選用',
    '표시 옵션': '顯示選項',
    '필요한 순간 놓치지 않기': '不錯過重要時刻',
    '한눈에 보는 일정': '一眼掌握行程',
    '화면 및 달력': '顯示與行事曆',
    '화면 및 일정': '顯示與行程',
    '화면과 기능 사용': '畫面與功能使用',
  },
};
